//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.30 at 11:39:15 AM CEST 
//


package es.rickyepoderi.wbxml.bind.syncml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sharedMem",
    "freeMem",
    "freeID"
})
@XmlRootElement(name = "Mem", namespace="syncml:metinf")
public class Mem {

    @XmlElement(name = "SharedMem", namespace="syncml:metinf")
    protected SharedMem sharedMem;
    @XmlElement(name = "FreeMem", namespace="syncml:metinf", required = true)
    protected String freeMem;
    @XmlElement(name = "FreeID", namespace="syncml:metinf", required = true)
    protected String freeID;

    /**
     * Gets the value of the sharedMem property.
     * 
     * @return
     *     possible object is
     *     {@link SharedMem }
     *     
     */
    public SharedMem getSharedMem() {
        return sharedMem;
    }

    /**
     * Sets the value of the sharedMem property.
     * 
     * @param value
     *     allowed object is
     *     {@link SharedMem }
     *     
     */
    public void setSharedMem(SharedMem value) {
        this.sharedMem = value;
    }

    /**
     * Gets the value of the freeMem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreeMem() {
        return freeMem;
    }

    /**
     * Sets the value of the freeMem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreeMem(String value) {
        this.freeMem = value;
    }

    /**
     * Gets the value of the freeID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreeID() {
        return freeID;
    }

    /**
     * Sets the value of the freeID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreeID(String value) {
        this.freeID = value;
    }

}
