//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.30 at 11:39:15 AM CEST 
//


package es.rickyepoderi.wbxml.bind.syncml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the es.rickyepoderi.wbxml.syncml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: es.rickyepoderi.wbxml.syncml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Atomic }
     * 
     */
    public Atomic createAtomic() {
        return new Atomic();
    }

    /**
     * Create an instance of {@link Anchor }
     * 
     */
    public Anchor createAnchor() {
        return new Anchor();
    }

    /**
     * Create an instance of {@link NoResp }
     * 
     */
    public NoResp createNoResp() {
        return new NoResp();
    }

    /**
     * Create an instance of {@link Replace }
     * 
     */
    public Replace createReplace() {
        return new Replace();
    }

    /**
     * Create an instance of {@link Sync }
     * 
     */
    public Sync createSync() {
        return new Sync();
    }

    /**
     * Create an instance of {@link Delete }
     * 
     */
    public Delete createDelete() {
        return new Delete();
    }

    /**
     * Create an instance of {@link Get }
     * 
     */
    public Get createGet() {
        return new Get();
    }

    /**
     * Create an instance of {@link Alert }
     * 
     */
    public Alert createAlert() {
        return new Alert();
    }

    /**
     * Create an instance of {@link EMI }
     * 
     */
    public EMI createEMI() {
        return new EMI();
    }

    /**
     * Create an instance of {@link Mem }
     * 
     */
    public Mem createMem() {
        return new Mem();
    }

    /**
     * Create an instance of {@link Item }
     * 
     */
    public Item createItem() {
        return new Item();
    }

    /**
     * Create an instance of {@link MapItem }
     * 
     */
    public MapItem createMapItem() {
        return new MapItem();
    }

    /**
     * Create an instance of {@link Put }
     * 
     */
    public Put createPut() {
        return new Put();
    }

    /**
     * Create an instance of {@link Results }
     * 
     */
    public Results createResults() {
        return new Results();
    }

    /**
     * Create an instance of {@link Final }
     * 
     */
    public Final createFinal() {
        return new Final();
    }

    /**
     * Create an instance of {@link Meta }
     * 
     */
    public Meta createMeta() {
        return new Meta();
    }

    /**
     * Create an instance of {@link SftDel }
     * 
     */
    public SftDel createSftDel() {
        return new SftDel();
    }

    /**
     * Create an instance of {@link Archive }
     * 
     */
    public Archive createArchive() {
        return new Archive();
    }

    /**
     * Create an instance of {@link Sequence }
     * 
     */
    public Sequence createSequence() {
        return new Sequence();
    }

    /**
     * Create an instance of {@link SharedMem }
     * 
     */
    public SharedMem createSharedMem() {
        return new SharedMem();
    }

    /**
     * Create an instance of {@link SyncML }
     * 
     */
    public SyncML createSyncML() {
        return new SyncML();
    }

    /**
     * Create an instance of {@link Target }
     * 
     */
    public Target createTarget() {
        return new Target();
    }

    /**
     * Create an instance of {@link Map }
     * 
     */
    public Map createMap() {
        return new Map();
    }

    /**
     * Create an instance of {@link Exec }
     * 
     */
    public Exec createExec() {
        return new Exec();
    }

    /**
     * Create an instance of {@link Add }
     * 
     */
    public Add createAdd() {
        return new Add();
    }

    /**
     * Create an instance of {@link Copy }
     * 
     */
    public Copy createCopy() {
        return new Copy();
    }

    /**
     * Create an instance of {@link SyncHdr }
     * 
     */
    public SyncHdr createSyncHdr() {
        return new SyncHdr();
    }

    /**
     * Create an instance of {@link SourceRef }
     * 
     */
    public SourceRef createSourceRef() {
        return new SourceRef();
    }

    /**
     * Create an instance of {@link SyncBody }
     * 
     */
    public SyncBody createSyncBody() {
        return new SyncBody();
    }

    /**
     * Create an instance of {@link NoResults }
     * 
     */
    public NoResults createNoResults() {
        return new NoResults();
    }

    /**
     * Create an instance of {@link TargetRef }
     * 
     */
    public TargetRef createTargetRef() {
        return new TargetRef();
    }

    /**
     * Create an instance of {@link MoreData }
     * 
     */
    public MoreData createMoreData() {
        return new MoreData();
    }

    /**
     * Create an instance of {@link Status }
     * 
     */
    public Status createStatus() {
        return new Status();
    }

    /**
     * Create an instance of {@link Chal }
     * 
     */
    public Chal createChal() {
        return new Chal();
    }

    /**
     * Create an instance of {@link Source }
     * 
     */
    public Source createSource() {
        return new Source();
    }

    /**
     * Create an instance of {@link Cred }
     * 
     */
    public Cred createCred() {
        return new Cred();
    }

    /**
     * Create an instance of {@link Search }
     * 
     */
    public Search createSearch() {
        return new Search();
    }

}
