//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.30 at 11:39:15 AM CEST 
//


package es.rickyepoderi.wbxml.bind.syncml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cmdID",
    "noResp",
    "meta",
    "addOrReplaceOrDeleteOrCopyOrAtomicOrMapOrSyncOrGetOrAlertOrExec"
})
@XmlRootElement(name = "Sequence", namespace="SYNCML:SYNCML1.1")
public class Sequence {

    @XmlElement(name = "CmdID", namespace="SYNCML:SYNCML1.1", required = true)
    protected String cmdID;
    @XmlElement(name = "NoResp", namespace="SYNCML:SYNCML1.1")
    protected NoResp noResp;
    @XmlElement(name = "Meta", namespace="SYNCML:SYNCML1.1")
    protected Meta meta;
    @XmlElements({
        @XmlElement(name = "Add", namespace="SYNCML:SYNCML1.1", required = true, type = Add.class),
        @XmlElement(name = "Replace", namespace="SYNCML:SYNCML1.1", required = true, type = Replace.class),
        @XmlElement(name = "Delete", namespace="SYNCML:SYNCML1.1", required = true, type = Delete.class),
        @XmlElement(name = "Copy", namespace="SYNCML:SYNCML1.1", required = true, type = Copy.class),
        @XmlElement(name = "Atomic", namespace="SYNCML:SYNCML1.1", required = true, type = Atomic.class),
        @XmlElement(name = "Map", namespace="SYNCML:SYNCML1.1", required = true, type = Map.class),
        @XmlElement(name = "Sync", namespace="SYNCML:SYNCML1.1", required = true, type = Sync.class),
        @XmlElement(name = "Get", namespace="SYNCML:SYNCML1.1", required = true, type = Get.class),
        @XmlElement(name = "Alert", namespace="SYNCML:SYNCML1.1", required = true, type = Alert.class),
        @XmlElement(name = "Exec", namespace="SYNCML:SYNCML1.1", required = true, type = Exec.class)
    })
    protected List<Object> addOrReplaceOrDeleteOrCopyOrAtomicOrMapOrSyncOrGetOrAlertOrExec;

    /**
     * Gets the value of the cmdID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCmdID() {
        return cmdID;
    }

    /**
     * Sets the value of the cmdID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCmdID(String value) {
        this.cmdID = value;
    }

    /**
     * Gets the value of the noResp property.
     * 
     * @return
     *     possible object is
     *     {@link NoResp }
     *     
     */
    public NoResp getNoResp() {
        return noResp;
    }

    /**
     * Sets the value of the noResp property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoResp }
     *     
     */
    public void setNoResp(NoResp value) {
        this.noResp = value;
    }

    /**
     * Gets the value of the meta property.
     * 
     * @return
     *     possible object is
     *     {@link Meta }
     *     
     */
    public Meta getMeta() {
        return meta;
    }

    /**
     * Sets the value of the meta property.
     * 
     * @param value
     *     allowed object is
     *     {@link Meta }
     *     
     */
    public void setMeta(Meta value) {
        this.meta = value;
    }

    /**
     * Gets the value of the addOrReplaceOrDeleteOrCopyOrAtomicOrMapOrSyncOrGetOrAlertOrExec property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the addOrReplaceOrDeleteOrCopyOrAtomicOrMapOrSyncOrGetOrAlertOrExec property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAddOrReplaceOrDeleteOrCopyOrAtomicOrMapOrSyncOrGetOrAlertOrExec().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Add }
     * {@link Replace }
     * {@link Delete }
     * {@link Copy }
     * {@link Atomic }
     * {@link Map }
     * {@link Sync }
     * {@link Get }
     * {@link Alert }
     * {@link Exec }
     * 
     * 
     */
    public List<Object> getAddOrReplaceOrDeleteOrCopyOrAtomicOrMapOrSyncOrGetOrAlertOrExec() {
        if (addOrReplaceOrDeleteOrCopyOrAtomicOrMapOrSyncOrGetOrAlertOrExec == null) {
            addOrReplaceOrDeleteOrCopyOrAtomicOrMapOrSyncOrGetOrAlertOrExec = new ArrayList<Object>();
        }
        return this.addOrReplaceOrDeleteOrCopyOrAtomicOrMapOrSyncOrGetOrAlertOrExec;
    }

}
