//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.30 at 11:39:15 AM CEST 
//


package es.rickyepoderi.wbxml.bind.syncml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cmdID",
    "msgRef",
    "cmdRef",
    "cmd",
    "targetRef",
    "sourceRef",
    "cred",
    "chal",
    "data",
    "item"
})
@XmlRootElement(name = "Status", namespace="SYNCML:SYNCML1.1")
public class Status {

    @XmlElement(name = "CmdID", namespace="SYNCML:SYNCML1.1", required = true)
    protected String cmdID;
    @XmlElement(name = "MsgRef", namespace="SYNCML:SYNCML1.1", required = true)
    protected String msgRef;
    @XmlElement(name = "CmdRef", namespace="SYNCML:SYNCML1.1", required = true)
    protected String cmdRef;
    @XmlElement(name = "Cmd", namespace="SYNCML:SYNCML1.1", required = true)
    protected String cmd;
    @XmlElement(name = "TargetRef", namespace="SYNCML:SYNCML1.1")
    protected List<TargetRef> targetRef;
    @XmlElement(name = "SourceRef", namespace="SYNCML:SYNCML1.1")
    protected List<SourceRef> sourceRef;
    @XmlElement(name = "Cred", namespace="SYNCML:SYNCML1.1")
    protected Cred cred;
    @XmlElement(name = "Chal", namespace="SYNCML:SYNCML1.1")
    protected Chal chal;
    @XmlElement(name = "Data", namespace="SYNCML:SYNCML1.1", required = true)
    protected String data;
    @XmlElement(name = "Item", namespace="SYNCML:SYNCML1.1")
    protected List<Item> item;

    /**
     * Gets the value of the cmdID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCmdID() {
        return cmdID;
    }

    /**
     * Sets the value of the cmdID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCmdID(String value) {
        this.cmdID = value;
    }

    /**
     * Gets the value of the msgRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMsgRef() {
        return msgRef;
    }

    /**
     * Sets the value of the msgRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMsgRef(String value) {
        this.msgRef = value;
    }

    /**
     * Gets the value of the cmdRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCmdRef() {
        return cmdRef;
    }

    /**
     * Sets the value of the cmdRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCmdRef(String value) {
        this.cmdRef = value;
    }

    /**
     * Gets the value of the cmd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCmd() {
        return cmd;
    }

    /**
     * Sets the value of the cmd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCmd(String value) {
        this.cmd = value;
    }

    /**
     * Gets the value of the targetRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the targetRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTargetRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TargetRef }
     * 
     * 
     */
    public List<TargetRef> getTargetRef() {
        if (targetRef == null) {
            targetRef = new ArrayList<TargetRef>();
        }
        return this.targetRef;
    }

    /**
     * Gets the value of the sourceRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sourceRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSourceRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SourceRef }
     * 
     * 
     */
    public List<SourceRef> getSourceRef() {
        if (sourceRef == null) {
            sourceRef = new ArrayList<SourceRef>();
        }
        return this.sourceRef;
    }

    /**
     * Gets the value of the cred property.
     * 
     * @return
     *     possible object is
     *     {@link Cred }
     *     
     */
    public Cred getCred() {
        return cred;
    }

    /**
     * Sets the value of the cred property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cred }
     *     
     */
    public void setCred(Cred value) {
        this.cred = value;
    }

    /**
     * Gets the value of the chal property.
     * 
     * @return
     *     possible object is
     *     {@link Chal }
     *     
     */
    public Chal getChal() {
        return chal;
    }

    /**
     * Sets the value of the chal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Chal }
     *     
     */
    public void setChal(Chal value) {
        this.chal = value;
    }

    /**
     * Gets the value of the data property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getData() {
        return data;
    }

    /**
     * Sets the value of the data property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setData(String value) {
        this.data = value;
    }

    /**
     * Gets the value of the item property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the item property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Item }
     * 
     * 
     */
    public List<Item> getItem() {
        if (item == null) {
            item = new ArrayList<Item>();
        }
        return this.item;
    }

}
