//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.30 at 11:39:15 AM CEST 
//


package es.rickyepoderi.wbxml.bind.syncml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "alertOrAtomicOrCopyOrExecOrGetOrMapOrPutOrResultsOrSearchOrSequenceOrStatusOrSyncOrAddOrReplaceOrDelete",
    "_final"
})
@XmlRootElement(name = "SyncBody", namespace="SYNCML:SYNCML1.1")
public class SyncBody {

    @XmlElements({
        @XmlElement(name = "Alert", namespace="SYNCML:SYNCML1.1", required = true, type = Alert.class),
        @XmlElement(name = "Atomic", namespace="SYNCML:SYNCML1.1", required = true, type = Atomic.class),
        @XmlElement(name = "Copy", namespace="SYNCML:SYNCML1.1", required = true, type = Copy.class),
        @XmlElement(name = "Exec", namespace="SYNCML:SYNCML1.1", required = true, type = Exec.class),
        @XmlElement(name = "Get", namespace="SYNCML:SYNCML1.1", required = true, type = Get.class),
        @XmlElement(name = "Map", namespace="SYNCML:SYNCML1.1", required = true, type = Map.class),
        @XmlElement(name = "Put", namespace="SYNCML:SYNCML1.1", required = true, type = Put.class),
        @XmlElement(name = "Results", namespace="SYNCML:SYNCML1.1", required = true, type = Results.class),
        @XmlElement(name = "Search", namespace="SYNCML:SYNCML1.1", required = true, type = Search.class),
        @XmlElement(name = "Sequence", namespace="SYNCML:SYNCML1.1", required = true, type = Sequence.class),
        @XmlElement(name = "Status", namespace="SYNCML:SYNCML1.1", required = true, type = Status.class),
        @XmlElement(name = "Sync", namespace="SYNCML:SYNCML1.1", required = true, type = Sync.class),
        @XmlElement(name = "Add", namespace="SYNCML:SYNCML1.1", required = true, type = Add.class),
        @XmlElement(name = "Replace", namespace="SYNCML:SYNCML1.1", required = true, type = Replace.class),
        @XmlElement(name = "Delete", namespace="SYNCML:SYNCML1.1", required = true, type = Delete.class)
    })
    protected List<Object> alertOrAtomicOrCopyOrExecOrGetOrMapOrPutOrResultsOrSearchOrSequenceOrStatusOrSyncOrAddOrReplaceOrDelete;
    @XmlElement(name = "Final", namespace="SYNCML:SYNCML1.1")
    protected Final _final;

    /**
     * Gets the value of the alertOrAtomicOrCopyOrExecOrGetOrMapOrPutOrResultsOrSearchOrSequenceOrStatusOrSyncOrAddOrReplaceOrDelete property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the alertOrAtomicOrCopyOrExecOrGetOrMapOrPutOrResultsOrSearchOrSequenceOrStatusOrSyncOrAddOrReplaceOrDelete property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAlertOrAtomicOrCopyOrExecOrGetOrMapOrPutOrResultsOrSearchOrSequenceOrStatusOrSyncOrAddOrReplaceOrDelete().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Alert }
     * {@link Atomic }
     * {@link Copy }
     * {@link Exec }
     * {@link Get }
     * {@link Map }
     * {@link Put }
     * {@link Results }
     * {@link Search }
     * {@link Sequence }
     * {@link Status }
     * {@link Sync }
     * {@link Add }
     * {@link Replace }
     * {@link Delete }
     * 
     * 
     */
    public List<Object> getAlertOrAtomicOrCopyOrExecOrGetOrMapOrPutOrResultsOrSearchOrSequenceOrStatusOrSyncOrAddOrReplaceOrDelete() {
        if (alertOrAtomicOrCopyOrExecOrGetOrMapOrPutOrResultsOrSearchOrSequenceOrStatusOrSyncOrAddOrReplaceOrDelete == null) {
            alertOrAtomicOrCopyOrExecOrGetOrMapOrPutOrResultsOrSearchOrSequenceOrStatusOrSyncOrAddOrReplaceOrDelete = new ArrayList<Object>();
        }
        return this.alertOrAtomicOrCopyOrExecOrGetOrMapOrPutOrResultsOrSearchOrSequenceOrStatusOrSyncOrAddOrReplaceOrDelete;
    }

    /**
     * Gets the value of the final property.
     * 
     * @return
     *     possible object is
     *     {@link Final }
     *     
     */
    public Final getFinal() {
        return _final;
    }

    /**
     * Sets the value of the final property.
     * 
     * @param value
     *     allowed object is
     *     {@link Final }
     *     
     */
    public void setFinal(Final value) {
        this._final = value;
    }

}
