//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.30 at 11:39:15 AM CEST 
//


package es.rickyepoderi.wbxml.bind.syncml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cmdID",
    "noResp",
    "cred",
    "target",
    "source",
    "meta",
    "numberOfChanges",
    "addOrAtomicOrCopyOrDeleteOrReplaceOrSequence"
})
@XmlRootElement(name = "Sync", namespace="SYNCML:SYNCML1.1")
public class Sync {

    @XmlElement(name = "CmdID", namespace="SYNCML:SYNCML1.1", required = true)
    protected String cmdID;
    @XmlElement(name = "NoResp", namespace="SYNCML:SYNCML1.1")
    protected NoResp noResp;
    @XmlElement(name = "Cred", namespace="SYNCML:SYNCML1.1")
    protected Cred cred;
    @XmlElement(name = "Target", namespace="SYNCML:SYNCML1.1")
    protected Target target;
    @XmlElement(name = "Source", namespace="SYNCML:SYNCML1.1")
    protected Source source;
    @XmlElement(name = "Meta", namespace="SYNCML:SYNCML1.1")
    protected Meta meta;
    @XmlElement(name = "NumberOfChanges", namespace="SYNCML:SYNCML1.1")
    protected String numberOfChanges;
    @XmlElements({
        @XmlElement(name = "Add", namespace="SYNCML:SYNCML1.1", type = Add.class),
        @XmlElement(name = "Atomic", namespace="SYNCML:SYNCML1.1", type = Atomic.class),
        @XmlElement(name = "Copy", namespace="SYNCML:SYNCML1.1", type = Copy.class),
        @XmlElement(name = "Delete", namespace="SYNCML:SYNCML1.1", type = Delete.class),
        @XmlElement(name = "Replace", namespace="SYNCML:SYNCML1.1", type = Replace.class),
        @XmlElement(name = "Sequence", namespace="SYNCML:SYNCML1.1", type = Sequence.class)
    })
    protected List<Object> addOrAtomicOrCopyOrDeleteOrReplaceOrSequence;

    /**
     * Gets the value of the cmdID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCmdID() {
        return cmdID;
    }

    /**
     * Sets the value of the cmdID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCmdID(String value) {
        this.cmdID = value;
    }

    /**
     * Gets the value of the noResp property.
     * 
     * @return
     *     possible object is
     *     {@link NoResp }
     *     
     */
    public NoResp getNoResp() {
        return noResp;
    }

    /**
     * Sets the value of the noResp property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoResp }
     *     
     */
    public void setNoResp(NoResp value) {
        this.noResp = value;
    }

    /**
     * Gets the value of the cred property.
     * 
     * @return
     *     possible object is
     *     {@link Cred }
     *     
     */
    public Cred getCred() {
        return cred;
    }

    /**
     * Sets the value of the cred property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cred }
     *     
     */
    public void setCred(Cred value) {
        this.cred = value;
    }

    /**
     * Gets the value of the target property.
     * 
     * @return
     *     possible object is
     *     {@link Target }
     *     
     */
    public Target getTarget() {
        return target;
    }

    /**
     * Sets the value of the target property.
     * 
     * @param value
     *     allowed object is
     *     {@link Target }
     *     
     */
    public void setTarget(Target value) {
        this.target = value;
    }

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link Source }
     *     
     */
    public Source getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link Source }
     *     
     */
    public void setSource(Source value) {
        this.source = value;
    }

    /**
     * Gets the value of the meta property.
     * 
     * @return
     *     possible object is
     *     {@link Meta }
     *     
     */
    public Meta getMeta() {
        return meta;
    }

    /**
     * Sets the value of the meta property.
     * 
     * @param value
     *     allowed object is
     *     {@link Meta }
     *     
     */
    public void setMeta(Meta value) {
        this.meta = value;
    }

    /**
     * Gets the value of the numberOfChanges property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumberOfChanges() {
        return numberOfChanges;
    }

    /**
     * Sets the value of the numberOfChanges property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumberOfChanges(String value) {
        this.numberOfChanges = value;
    }

    /**
     * Gets the value of the addOrAtomicOrCopyOrDeleteOrReplaceOrSequence property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the addOrAtomicOrCopyOrDeleteOrReplaceOrSequence property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAddOrAtomicOrCopyOrDeleteOrReplaceOrSequence().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Add }
     * {@link Atomic }
     * {@link Copy }
     * {@link Delete }
     * {@link Replace }
     * {@link Sequence }
     * 
     * 
     */
    public List<Object> getAddOrAtomicOrCopyOrDeleteOrReplaceOrSequence() {
        if (addOrAtomicOrCopyOrDeleteOrReplaceOrSequence == null) {
            addOrAtomicOrCopyOrDeleteOrReplaceOrSequence = new ArrayList<Object>();
        }
        return this.addOrAtomicOrCopyOrDeleteOrReplaceOrSequence;
    }

}
