//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.25 at 05:48:09 PM CEST 
//


package es.rickyepoderi.wbxml.bind.wvcsp;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nickNameOrUserID"
})
@XmlRootElement(name = "AddNickList")
public class AddNickList {

    @XmlElements({
        @XmlElement(name = "NickName", type = NickName.class),
        @XmlElement(name = "UserID", type = UserID.class)
    })
    protected List<Object> nickNameOrUserID;

    /**
     * Gets the value of the nickNameOrUserID property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nickNameOrUserID property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNickNameOrUserID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NickName }
     * {@link UserID }
     * 
     * 
     */
    public List<Object> getNickNameOrUserID() {
        if (nickNameOrUserID == null) {
            nickNameOrUserID = new ArrayList<Object>();
        }
        return this.nickNameOrUserID;
    }

}
