//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.25 at 05:48:09 PM CEST 
//


package es.rickyepoderi.wbxml.bind.wvcsp;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "inUse",
    "entityListOrAddListOrRemoveList"
})
@XmlRootElement(name = "BlockList")
public class BlockList {

    @XmlElement(name = "InUse")
    protected String inUse;
    @XmlElements({
        @XmlElement(name = "EntityList", type = EntityList.class),
        @XmlElement(name = "AddList", type = AddList.class),
        @XmlElement(name = "RemoveList", type = RemoveList.class)
    })
    protected List<Object> entityListOrAddListOrRemoveList;

    /**
     * Gets the value of the inUse property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInUse() {
        return inUse;
    }

    /**
     * Sets the value of the inUse property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInUse(String value) {
        this.inUse = value;
    }

    /**
     * Gets the value of the entityListOrAddListOrRemoveList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the entityListOrAddListOrRemoveList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEntityListOrAddListOrRemoveList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EntityList }
     * {@link AddList }
     * {@link RemoveList }
     * 
     * 
     */
    public List<Object> getEntityListOrAddListOrRemoveList() {
        if (entityListOrAddListOrRemoveList == null) {
            entityListOrAddListOrRemoveList = new ArrayList<Object>();
        }
        return this.entityListOrAddListOrRemoveList;
    }

}
