//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.25 at 05:48:09 PM CEST 
//


package es.rickyepoderi.wbxml.bind.wvcsp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "blockList",
    "grantList"
})
@XmlRootElement(name = "BlockEntity-Request")
public class BlockEntityRequest {

    @XmlElement(name = "BlockList")
    protected BlockList blockList;
    @XmlElement(name = "GrantList")
    protected GrantList grantList;

    /**
     * Gets the value of the blockList property.
     * 
     * @return
     *     possible object is
     *     {@link BlockList }
     *     
     */
    public BlockList getBlockList() {
        return blockList;
    }

    /**
     * Sets the value of the blockList property.
     * 
     * @param value
     *     allowed object is
     *     {@link BlockList }
     *     
     */
    public void setBlockList(BlockList value) {
        this.blockList = value;
    }

    /**
     * Gets the value of the grantList property.
     * 
     * @return
     *     possible object is
     *     {@link GrantList }
     *     
     */
    public GrantList getGrantList() {
        return grantList;
    }

    /**
     * Sets the value of the grantList property.
     * 
     * @param value
     *     allowed object is
     *     {@link GrantList }
     *     
     */
    public void setGrantList(GrantList value) {
        this.grantList = value;
    }

}
