//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.25 at 05:48:09 PM CEST 
//


package es.rickyepoderi.wbxml.bind.wvcsp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "inviteID",
    "recipient",
    "inviteNote",
    "urlList",
    "screenName"
})
@XmlRootElement(name = "CancelInvite-Request")
public class CancelInviteRequest {

    @XmlElement(name = "InviteID", required = true)
    protected String inviteID;
    @XmlElement(name = "Recipient", required = true)
    protected Recipient recipient;
    @XmlElement(name = "InviteNote")
    protected String inviteNote;
    @XmlElement(name = "URLList")
    protected URLList urlList;
    @XmlElement(name = "ScreenName")
    protected ScreenName screenName;

    /**
     * Gets the value of the inviteID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInviteID() {
        return inviteID;
    }

    /**
     * Sets the value of the inviteID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInviteID(String value) {
        this.inviteID = value;
    }

    /**
     * Gets the value of the recipient property.
     * 
     * @return
     *     possible object is
     *     {@link Recipient }
     *     
     */
    public Recipient getRecipient() {
        return recipient;
    }

    /**
     * Sets the value of the recipient property.
     * 
     * @param value
     *     allowed object is
     *     {@link Recipient }
     *     
     */
    public void setRecipient(Recipient value) {
        this.recipient = value;
    }

    /**
     * Gets the value of the inviteNote property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInviteNote() {
        return inviteNote;
    }

    /**
     * Sets the value of the inviteNote property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInviteNote(String value) {
        this.inviteNote = value;
    }

    /**
     * Gets the value of the urlList property.
     * 
     * @return
     *     possible object is
     *     {@link URLList }
     *     
     */
    public URLList getURLList() {
        return urlList;
    }

    /**
     * Sets the value of the urlList property.
     * 
     * @param value
     *     allowed object is
     *     {@link URLList }
     *     
     */
    public void setURLList(URLList value) {
        this.urlList = value;
    }

    /**
     * Gets the value of the screenName property.
     * 
     * @return
     *     possible object is
     *     {@link ScreenName }
     *     
     */
    public ScreenName getScreenName() {
        return screenName;
    }

    /**
     * Sets the value of the screenName property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScreenName }
     *     
     */
    public void setScreenName(ScreenName value) {
        this.screenName = value;
    }

}
