//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.25 at 05:48:09 PM CEST 
//


package es.rickyepoderi.wbxml.bind.wvcsp;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "clientType",
    "initialDeliveryMethod",
    "anyContentOrAcceptedCharSetOrAcceptedContentType",
    "acceptedTransferEncoding",
    "acceptedContentLength",
    "supportedBearer",
    "multiTrans",
    "parserSize",
    "supportedCIRMethod",
    "udpPort",
    "tcpAddress",
    "tcpPort",
    "serverPollMin",
    "defaultLanguage"
})
@XmlRootElement(name = "CapabilityList")
public class CapabilityList {

    @XmlElement(name = "ClientType", required = true)
    protected String clientType;
    @XmlElement(name = "InitialDeliveryMethod", required = true)
    protected String initialDeliveryMethod;
    @XmlElements({
        @XmlElement(name = "AnyContent", type = AnyContent.class),
        @XmlElement(name = "AcceptedCharSet", type = AcceptedCharSet.class),
        @XmlElement(name = "AcceptedContentType", type = AcceptedContentType.class)
    })
    protected List<Object> anyContentOrAcceptedCharSetOrAcceptedContentType;
    @XmlElement(name = "AcceptedTransferEncoding")
    protected List<AcceptedTransferEncoding> acceptedTransferEncoding;
    @XmlElement(name = "AcceptedContentLength", required = true)
    protected String acceptedContentLength;
    @XmlElement(name = "SupportedBearer")
    protected List<SupportedBearer> supportedBearer;
    @XmlElement(name = "MultiTrans", required = true)
    protected String multiTrans;
    @XmlElement(name = "ParserSize", required = true)
    protected String parserSize;
    @XmlElement(name = "SupportedCIRMethod")
    protected List<SupportedCIRMethod> supportedCIRMethod;
    @XmlElement(name = "UDPPort")
    protected String udpPort;
    @XmlElement(name = "TCPAddress")
    protected String tcpAddress;
    @XmlElement(name = "TCPPort")
    protected String tcpPort;
    @XmlElement(name = "ServerPollMin")
    protected String serverPollMin;
    @XmlElement(name = "DefaultLanguage")
    protected String defaultLanguage;

    /**
     * Gets the value of the clientType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientType() {
        return clientType;
    }

    /**
     * Sets the value of the clientType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientType(String value) {
        this.clientType = value;
    }

    /**
     * Gets the value of the initialDeliveryMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInitialDeliveryMethod() {
        return initialDeliveryMethod;
    }

    /**
     * Sets the value of the initialDeliveryMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInitialDeliveryMethod(String value) {
        this.initialDeliveryMethod = value;
    }

    /**
     * Gets the value of the anyContentOrAcceptedCharSetOrAcceptedContentType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the anyContentOrAcceptedCharSetOrAcceptedContentType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAnyContentOrAcceptedCharSetOrAcceptedContentType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AnyContent }
     * {@link AcceptedCharSet }
     * {@link AcceptedContentType }
     * 
     * 
     */
    public List<Object> getAnyContentOrAcceptedCharSetOrAcceptedContentType() {
        if (anyContentOrAcceptedCharSetOrAcceptedContentType == null) {
            anyContentOrAcceptedCharSetOrAcceptedContentType = new ArrayList<Object>();
        }
        return this.anyContentOrAcceptedCharSetOrAcceptedContentType;
    }

    /**
     * Gets the value of the acceptedTransferEncoding property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the acceptedTransferEncoding property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAcceptedTransferEncoding().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AcceptedTransferEncoding }
     * 
     * 
     */
    public List<AcceptedTransferEncoding> getAcceptedTransferEncoding() {
        if (acceptedTransferEncoding == null) {
            acceptedTransferEncoding = new ArrayList<AcceptedTransferEncoding>();
        }
        return this.acceptedTransferEncoding;
    }

    /**
     * Gets the value of the acceptedContentLength property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcceptedContentLength() {
        return acceptedContentLength;
    }

    /**
     * Sets the value of the acceptedContentLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcceptedContentLength(String value) {
        this.acceptedContentLength = value;
    }

    /**
     * Gets the value of the supportedBearer property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the supportedBearer property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSupportedBearer().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SupportedBearer }
     * 
     * 
     */
    public List<SupportedBearer> getSupportedBearer() {
        if (supportedBearer == null) {
            supportedBearer = new ArrayList<SupportedBearer>();
        }
        return this.supportedBearer;
    }

    /**
     * Gets the value of the multiTrans property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMultiTrans() {
        return multiTrans;
    }

    /**
     * Sets the value of the multiTrans property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMultiTrans(String value) {
        this.multiTrans = value;
    }

    /**
     * Gets the value of the parserSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParserSize() {
        return parserSize;
    }

    /**
     * Sets the value of the parserSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParserSize(String value) {
        this.parserSize = value;
    }

    /**
     * Gets the value of the supportedCIRMethod property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the supportedCIRMethod property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSupportedCIRMethod().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SupportedCIRMethod }
     * 
     * 
     */
    public List<SupportedCIRMethod> getSupportedCIRMethod() {
        if (supportedCIRMethod == null) {
            supportedCIRMethod = new ArrayList<SupportedCIRMethod>();
        }
        return this.supportedCIRMethod;
    }

    /**
     * Gets the value of the udpPort property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUDPPort() {
        return udpPort;
    }

    /**
     * Sets the value of the udpPort property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUDPPort(String value) {
        this.udpPort = value;
    }

    /**
     * Gets the value of the tcpAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTCPAddress() {
        return tcpAddress;
    }

    /**
     * Sets the value of the tcpAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTCPAddress(String value) {
        this.tcpAddress = value;
    }

    /**
     * Gets the value of the tcpPort property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTCPPort() {
        return tcpPort;
    }

    /**
     * Sets the value of the tcpPort property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTCPPort(String value) {
        this.tcpPort = value;
    }

    /**
     * Gets the value of the serverPollMin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServerPollMin() {
        return serverPollMin;
    }

    /**
     * Sets the value of the serverPollMin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServerPollMin(String value) {
        this.serverPollMin = value;
    }

    /**
     * Gets the value of the defaultLanguage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultLanguage() {
        return defaultLanguage;
    }

    /**
     * Sets the value of the defaultLanguage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultLanguage(String value) {
        this.defaultLanguage = value;
    }

}
