//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.25 at 05:48:09 PM CEST 
//


package es.rickyepoderi.wbxml.bind.wvcsp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "gcli",
    "ccli",
    "dcli",
    "mcls"
})
@XmlRootElement(name = "ContListFunc")
public class ContListFunc {

    @XmlElement(name = "GCLI")
    protected GCLI gcli;
    @XmlElement(name = "CCLI")
    protected CCLI ccli;
    @XmlElement(name = "DCLI")
    protected DCLI dcli;
    @XmlElement(name = "MCLS")
    protected MCLS mcls;

    /**
     * Gets the value of the gcli property.
     * 
     * @return
     *     possible object is
     *     {@link GCLI }
     *     
     */
    public GCLI getGCLI() {
        return gcli;
    }

    /**
     * Sets the value of the gcli property.
     * 
     * @param value
     *     allowed object is
     *     {@link GCLI }
     *     
     */
    public void setGCLI(GCLI value) {
        this.gcli = value;
    }

    /**
     * Gets the value of the ccli property.
     * 
     * @return
     *     possible object is
     *     {@link CCLI }
     *     
     */
    public CCLI getCCLI() {
        return ccli;
    }

    /**
     * Sets the value of the ccli property.
     * 
     * @param value
     *     allowed object is
     *     {@link CCLI }
     *     
     */
    public void setCCLI(CCLI value) {
        this.ccli = value;
    }

    /**
     * Gets the value of the dcli property.
     * 
     * @return
     *     possible object is
     *     {@link DCLI }
     *     
     */
    public DCLI getDCLI() {
        return dcli;
    }

    /**
     * Sets the value of the dcli property.
     * 
     * @param value
     *     allowed object is
     *     {@link DCLI }
     *     
     */
    public void setDCLI(DCLI value) {
        this.dcli = value;
    }

    /**
     * Gets the value of the mcls property.
     * 
     * @return
     *     possible object is
     *     {@link MCLS }
     *     
     */
    public MCLS getMCLS() {
        return mcls;
    }

    /**
     * Sets the value of the mcls property.
     * 
     * @param value
     *     allowed object is
     *     {@link MCLS }
     *     
     */
    public void setMCLS(MCLS value) {
        this.mcls = value;
    }

}
