//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.25 at 05:48:09 PM CEST 
//


package es.rickyepoderi.wbxml.bind.wvcsp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "serviceFunc",
    "searchFunc",
    "inviteFunc"
})
@XmlRootElement(name = "FundamentalFeat")
public class FundamentalFeat {

    @XmlElement(name = "ServiceFunc")
    protected ServiceFunc serviceFunc;
    @XmlElement(name = "SearchFunc")
    protected SearchFunc searchFunc;
    @XmlElement(name = "InviteFunc")
    protected InviteFunc inviteFunc;

    /**
     * Gets the value of the serviceFunc property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceFunc }
     *     
     */
    public ServiceFunc getServiceFunc() {
        return serviceFunc;
    }

    /**
     * Sets the value of the serviceFunc property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceFunc }
     *     
     */
    public void setServiceFunc(ServiceFunc value) {
        this.serviceFunc = value;
    }

    /**
     * Gets the value of the searchFunc property.
     * 
     * @return
     *     possible object is
     *     {@link SearchFunc }
     *     
     */
    public SearchFunc getSearchFunc() {
        return searchFunc;
    }

    /**
     * Sets the value of the searchFunc property.
     * 
     * @param value
     *     allowed object is
     *     {@link SearchFunc }
     *     
     */
    public void setSearchFunc(SearchFunc value) {
        this.searchFunc = value;
    }

    /**
     * Gets the value of the inviteFunc property.
     * 
     * @return
     *     possible object is
     *     {@link InviteFunc }
     *     
     */
    public InviteFunc getInviteFunc() {
        return inviteFunc;
    }

    /**
     * Sets the value of the inviteFunc property.
     * 
     * @param value
     *     allowed object is
     *     {@link InviteFunc }
     *     
     */
    public void setInviteFunc(InviteFunc value) {
        this.inviteFunc = value;
    }

}
