//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.25 at 05:48:09 PM CEST 
//


package es.rickyepoderi.wbxml.bind.wvcsp;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "result",
    "defaultAttributeList",
    "presence"
})
@XmlRootElement(name = "GetAttributeList-Response")
public class GetAttributeListResponse {

    @XmlElement(name = "Result", required = true)
    protected Result result;
    @XmlElement(name = "DefaultAttributeList")
    protected DefaultAttributeList defaultAttributeList;
    @XmlElement(name = "Presence")
    protected List<Presence> presence;

    /**
     * Gets the value of the result property.
     * 
     * @return
     *     possible object is
     *     {@link Result }
     *     
     */
    public Result getResult() {
        return result;
    }

    /**
     * Sets the value of the result property.
     * 
     * @param value
     *     allowed object is
     *     {@link Result }
     *     
     */
    public void setResult(Result value) {
        this.result = value;
    }

    /**
     * Gets the value of the defaultAttributeList property.
     * 
     * @return
     *     possible object is
     *     {@link DefaultAttributeList }
     *     
     */
    public DefaultAttributeList getDefaultAttributeList() {
        return defaultAttributeList;
    }

    /**
     * Sets the value of the defaultAttributeList property.
     * 
     * @param value
     *     allowed object is
     *     {@link DefaultAttributeList }
     *     
     */
    public void setDefaultAttributeList(DefaultAttributeList value) {
        this.defaultAttributeList = value;
    }

    /**
     * Gets the value of the presence property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the presence property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPresence().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Presence }
     * 
     * 
     */
    public List<Presence> getPresence() {
        if (presence == null) {
            presence = new ArrayList<Presence>();
        }
        return this.presence;
    }

}
