//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.25 at 05:48:09 PM CEST 
//


package es.rickyepoderi.wbxml.bind.wvcsp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "groupProperties",
    "ownProperties"
})
@XmlRootElement(name = "GetGroupProps-Response")
public class GetGroupPropsResponse {

    @XmlElement(name = "GroupProperties", required = true)
    protected GroupProperties groupProperties;
    @XmlElement(name = "OwnProperties", required = true)
    protected OwnProperties ownProperties;

    /**
     * Gets the value of the groupProperties property.
     * 
     * @return
     *     possible object is
     *     {@link GroupProperties }
     *     
     */
    public GroupProperties getGroupProperties() {
        return groupProperties;
    }

    /**
     * Sets the value of the groupProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link GroupProperties }
     *     
     */
    public void setGroupProperties(GroupProperties value) {
        this.groupProperties = value;
    }

    /**
     * Gets the value of the ownProperties property.
     * 
     * @return
     *     possible object is
     *     {@link OwnProperties }
     *     
     */
    public OwnProperties getOwnProperties() {
        return ownProperties;
    }

    /**
     * Sets the value of the ownProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link OwnProperties }
     *     
     */
    public void setOwnProperties(OwnProperties value) {
        this.ownProperties = value;
    }

}
