//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.25 at 05:48:09 PM CEST 
//


package es.rickyepoderi.wbxml.bind.wvcsp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "groupMgmtFunc",
    "groupUseFunc",
    "groupAuthFunc"
})
@XmlRootElement(name = "GroupFeat")
public class GroupFeat {

    @XmlElement(name = "GroupMgmtFunc")
    protected GroupMgmtFunc groupMgmtFunc;
    @XmlElement(name = "GroupUseFunc")
    protected GroupUseFunc groupUseFunc;
    @XmlElement(name = "GroupAuthFunc")
    protected GroupAuthFunc groupAuthFunc;

    /**
     * Gets the value of the groupMgmtFunc property.
     * 
     * @return
     *     possible object is
     *     {@link GroupMgmtFunc }
     *     
     */
    public GroupMgmtFunc getGroupMgmtFunc() {
        return groupMgmtFunc;
    }

    /**
     * Sets the value of the groupMgmtFunc property.
     * 
     * @param value
     *     allowed object is
     *     {@link GroupMgmtFunc }
     *     
     */
    public void setGroupMgmtFunc(GroupMgmtFunc value) {
        this.groupMgmtFunc = value;
    }

    /**
     * Gets the value of the groupUseFunc property.
     * 
     * @return
     *     possible object is
     *     {@link GroupUseFunc }
     *     
     */
    public GroupUseFunc getGroupUseFunc() {
        return groupUseFunc;
    }

    /**
     * Sets the value of the groupUseFunc property.
     * 
     * @param value
     *     allowed object is
     *     {@link GroupUseFunc }
     *     
     */
    public void setGroupUseFunc(GroupUseFunc value) {
        this.groupUseFunc = value;
    }

    /**
     * Gets the value of the groupAuthFunc property.
     * 
     * @return
     *     possible object is
     *     {@link GroupAuthFunc }
     *     
     */
    public GroupAuthFunc getGroupAuthFunc() {
        return groupAuthFunc;
    }

    /**
     * Sets the value of the groupAuthFunc property.
     * 
     * @param value
     *     allowed object is
     *     {@link GroupAuthFunc }
     *     
     */
    public void setGroupAuthFunc(GroupAuthFunc value) {
        this.groupAuthFunc = value;
    }

}
