//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.25 at 05:48:09 PM CEST 
//


package es.rickyepoderi.wbxml.bind.wvcsp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "getgm",
    "addgm",
    "rmvgm",
    "mbrac",
    "rejec"
})
@XmlRootElement(name = "GroupAuthFunc")
public class GroupAuthFunc {

    @XmlElement(name = "GETGM")
    protected GETGM getgm;
    @XmlElement(name = "ADDGM")
    protected ADDGM addgm;
    @XmlElement(name = "RMVGM")
    protected RMVGM rmvgm;
    @XmlElement(name = "MBRAC")
    protected MBRAC mbrac;
    @XmlElement(name = "REJEC")
    protected REJEC rejec;

    /**
     * Gets the value of the getgm property.
     * 
     * @return
     *     possible object is
     *     {@link GETGM }
     *     
     */
    public GETGM getGETGM() {
        return getgm;
    }

    /**
     * Sets the value of the getgm property.
     * 
     * @param value
     *     allowed object is
     *     {@link GETGM }
     *     
     */
    public void setGETGM(GETGM value) {
        this.getgm = value;
    }

    /**
     * Gets the value of the addgm property.
     * 
     * @return
     *     possible object is
     *     {@link ADDGM }
     *     
     */
    public ADDGM getADDGM() {
        return addgm;
    }

    /**
     * Sets the value of the addgm property.
     * 
     * @param value
     *     allowed object is
     *     {@link ADDGM }
     *     
     */
    public void setADDGM(ADDGM value) {
        this.addgm = value;
    }

    /**
     * Gets the value of the rmvgm property.
     * 
     * @return
     *     possible object is
     *     {@link RMVGM }
     *     
     */
    public RMVGM getRMVGM() {
        return rmvgm;
    }

    /**
     * Sets the value of the rmvgm property.
     * 
     * @param value
     *     allowed object is
     *     {@link RMVGM }
     *     
     */
    public void setRMVGM(RMVGM value) {
        this.rmvgm = value;
    }

    /**
     * Gets the value of the mbrac property.
     * 
     * @return
     *     possible object is
     *     {@link MBRAC }
     *     
     */
    public MBRAC getMBRAC() {
        return mbrac;
    }

    /**
     * Sets the value of the mbrac property.
     * 
     * @param value
     *     allowed object is
     *     {@link MBRAC }
     *     
     */
    public void setMBRAC(MBRAC value) {
        this.mbrac = value;
    }

    /**
     * Gets the value of the rejec property.
     * 
     * @return
     *     possible object is
     *     {@link REJEC }
     *     
     */
    public REJEC getREJEC() {
        return rejec;
    }

    /**
     * Sets the value of the rejec property.
     * 
     * @param value
     *     allowed object is
     *     {@link REJEC }
     *     
     */
    public void setREJEC(REJEC value) {
        this.rejec = value;
    }

}
