//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.25 at 05:48:09 PM CEST 
//


package es.rickyepoderi.wbxml.bind.wvcsp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "groupID",
    "joined",
    "left",
    "groupProperties",
    "ownProperties"
})
@XmlRootElement(name = "GroupChangeNotice")
public class GroupChangeNotice {

    @XmlElement(name = "GroupID", required = true)
    protected GroupID groupID;
    @XmlElement(name = "Joined")
    protected Joined joined;
    @XmlElement(name = "Left")
    protected Left left;
    @XmlElement(name = "GroupProperties")
    protected GroupProperties groupProperties;
    @XmlElement(name = "OwnProperties")
    protected OwnProperties ownProperties;

    /**
     * Gets the value of the groupID property.
     * 
     * @return
     *     possible object is
     *     {@link GroupID }
     *     
     */
    public GroupID getGroupID() {
        return groupID;
    }

    /**
     * Sets the value of the groupID property.
     * 
     * @param value
     *     allowed object is
     *     {@link GroupID }
     *     
     */
    public void setGroupID(GroupID value) {
        this.groupID = value;
    }

    /**
     * Gets the value of the joined property.
     * 
     * @return
     *     possible object is
     *     {@link Joined }
     *     
     */
    public Joined getJoined() {
        return joined;
    }

    /**
     * Sets the value of the joined property.
     * 
     * @param value
     *     allowed object is
     *     {@link Joined }
     *     
     */
    public void setJoined(Joined value) {
        this.joined = value;
    }

    /**
     * Gets the value of the left property.
     * 
     * @return
     *     possible object is
     *     {@link Left }
     *     
     */
    public Left getLeft() {
        return left;
    }

    /**
     * Sets the value of the left property.
     * 
     * @param value
     *     allowed object is
     *     {@link Left }
     *     
     */
    public void setLeft(Left value) {
        this.left = value;
    }

    /**
     * Gets the value of the groupProperties property.
     * 
     * @return
     *     possible object is
     *     {@link GroupProperties }
     *     
     */
    public GroupProperties getGroupProperties() {
        return groupProperties;
    }

    /**
     * Sets the value of the groupProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link GroupProperties }
     *     
     */
    public void setGroupProperties(GroupProperties value) {
        this.groupProperties = value;
    }

    /**
     * Gets the value of the ownProperties property.
     * 
     * @return
     *     possible object is
     *     {@link OwnProperties }
     *     
     */
    public OwnProperties getOwnProperties() {
        return ownProperties;
    }

    /**
     * Sets the value of the ownProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link OwnProperties }
     *     
     */
    public void setOwnProperties(OwnProperties value) {
        this.ownProperties = value;
    }

}
