//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.25 at 05:48:09 PM CEST 
//


package es.rickyepoderi.wbxml.bind.wvcsp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "glblu",
    "blent"
})
@XmlRootElement(name = "IMAuthFunc")
public class IMAuthFunc {

    @XmlElement(name = "GLBLU")
    protected GLBLU glblu;
    @XmlElement(name = "BLENT")
    protected BLENT blent;

    /**
     * Gets the value of the glblu property.
     * 
     * @return
     *     possible object is
     *     {@link GLBLU }
     *     
     */
    public GLBLU getGLBLU() {
        return glblu;
    }

    /**
     * Sets the value of the glblu property.
     * 
     * @param value
     *     allowed object is
     *     {@link GLBLU }
     *     
     */
    public void setGLBLU(GLBLU value) {
        this.glblu = value;
    }

    /**
     * Gets the value of the blent property.
     * 
     * @return
     *     possible object is
     *     {@link BLENT }
     *     
     */
    public BLENT getBLENT() {
        return blent;
    }

    /**
     * Sets the value of the blent property.
     * 
     * @param value
     *     allowed object is
     *     {@link BLENT }
     *     
     */
    public void setBLENT(BLENT value) {
        this.blent = value;
    }

}
