//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.25 at 05:48:09 PM CEST 
//


package es.rickyepoderi.wbxml.bind.wvcsp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "imSendFunc",
    "imReceiveFunc",
    "imAuthFunc"
})
@XmlRootElement(name = "IMFeat")
public class IMFeat {

    @XmlElement(name = "IMSendFunc")
    protected IMSendFunc imSendFunc;
    @XmlElement(name = "IMReceiveFunc")
    protected IMReceiveFunc imReceiveFunc;
    @XmlElement(name = "IMAuthFunc")
    protected IMAuthFunc imAuthFunc;

    /**
     * Gets the value of the imSendFunc property.
     * 
     * @return
     *     possible object is
     *     {@link IMSendFunc }
     *     
     */
    public IMSendFunc getIMSendFunc() {
        return imSendFunc;
    }

    /**
     * Sets the value of the imSendFunc property.
     * 
     * @param value
     *     allowed object is
     *     {@link IMSendFunc }
     *     
     */
    public void setIMSendFunc(IMSendFunc value) {
        this.imSendFunc = value;
    }

    /**
     * Gets the value of the imReceiveFunc property.
     * 
     * @return
     *     possible object is
     *     {@link IMReceiveFunc }
     *     
     */
    public IMReceiveFunc getIMReceiveFunc() {
        return imReceiveFunc;
    }

    /**
     * Sets the value of the imReceiveFunc property.
     * 
     * @param value
     *     allowed object is
     *     {@link IMReceiveFunc }
     *     
     */
    public void setIMReceiveFunc(IMReceiveFunc value) {
        this.imReceiveFunc = value;
    }

    /**
     * Gets the value of the imAuthFunc property.
     * 
     * @return
     *     possible object is
     *     {@link IMAuthFunc }
     *     
     */
    public IMAuthFunc getIMAuthFunc() {
        return imAuthFunc;
    }

    /**
     * Sets the value of the imAuthFunc property.
     * 
     * @param value
     *     allowed object is
     *     {@link IMAuthFunc }
     *     
     */
    public void setIMAuthFunc(IMAuthFunc value) {
        this.imAuthFunc = value;
    }

}
