//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.25 at 05:48:09 PM CEST 
//


package es.rickyepoderi.wbxml.bind.wvcsp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "invit",
    "cainv"
})
@XmlRootElement(name = "InviteFunc")
public class InviteFunc {

    @XmlElement(name = "INVIT")
    protected INVIT invit;
    @XmlElement(name = "CAINV")
    protected CAINV cainv;

    /**
     * Gets the value of the invit property.
     * 
     * @return
     *     possible object is
     *     {@link INVIT }
     *     
     */
    public INVIT getINVIT() {
        return invit;
    }

    /**
     * Sets the value of the invit property.
     * 
     * @param value
     *     allowed object is
     *     {@link INVIT }
     *     
     */
    public void setINVIT(INVIT value) {
        this.invit = value;
    }

    /**
     * Gets the value of the cainv property.
     * 
     * @return
     *     possible object is
     *     {@link CAINV }
     *     
     */
    public CAINV getCAINV() {
        return cainv;
    }

    /**
     * Sets the value of the cainv property.
     * 
     * @param value
     *     allowed object is
     *     {@link CAINV }
     *     
     */
    public void setCAINV(CAINV value) {
        this.cainv = value;
    }

}
