//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.25 at 05:48:09 PM CEST 
//


package es.rickyepoderi.wbxml.bind.wvcsp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "groupID",
    "screenName",
    "joinedRequest",
    "subscribeNotification"
})
@XmlRootElement(name = "JoinGroup-Request")
public class JoinGroupRequest {

    @XmlElement(name = "GroupID", required = true)
    protected GroupID groupID;
    @XmlElement(name = "ScreenName")
    protected ScreenName screenName;
    @XmlElement(name = "JoinedRequest", required = true)
    protected String joinedRequest;
    @XmlElement(name = "SubscribeNotification", required = true)
    protected String subscribeNotification;

    /**
     * Gets the value of the groupID property.
     * 
     * @return
     *     possible object is
     *     {@link GroupID }
     *     
     */
    public GroupID getGroupID() {
        return groupID;
    }

    /**
     * Sets the value of the groupID property.
     * 
     * @param value
     *     allowed object is
     *     {@link GroupID }
     *     
     */
    public void setGroupID(GroupID value) {
        this.groupID = value;
    }

    /**
     * Gets the value of the screenName property.
     * 
     * @return
     *     possible object is
     *     {@link ScreenName }
     *     
     */
    public ScreenName getScreenName() {
        return screenName;
    }

    /**
     * Sets the value of the screenName property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScreenName }
     *     
     */
    public void setScreenName(ScreenName value) {
        this.screenName = value;
    }

    /**
     * Gets the value of the joinedRequest property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJoinedRequest() {
        return joinedRequest;
    }

    /**
     * Sets the value of the joinedRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJoinedRequest(String value) {
        this.joinedRequest = value;
    }

    /**
     * Gets the value of the subscribeNotification property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubscribeNotification() {
        return subscribeNotification;
    }

    /**
     * Sets the value of the subscribeNotification property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubscribeNotification(String value) {
        this.subscribeNotification = value;
    }

}
