//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.25 at 05:48:09 PM CEST 
//


package es.rickyepoderi.wbxml.bind.wvcsp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "userID",
    "clientID",
    "password",
    "digestBytes",
    "digestSchema",
    "timeToLive",
    "sessionCookie"
})
@XmlRootElement(name = "Login-Request")
public class LoginRequest {

    @XmlElement(name = "UserID", required = true)
    protected UserID userID;
    @XmlElement(name = "ClientID", required = true)
    protected ClientID clientID;
    @XmlElement(name = "Password")
    protected String password;
    @XmlElement(name = "DigestBytes")
    protected String digestBytes;
    @XmlElement(name = "DigestSchema")
    protected String digestSchema;
    @XmlElement(name = "TimeToLive")
    protected String timeToLive;
    @XmlElement(name = "SessionCookie", required = true)
    protected String sessionCookie;

    /**
     * Gets the value of the userID property.
     * 
     * @return
     *     possible object is
     *     {@link UserID }
     *     
     */
    public UserID getUserID() {
        return userID;
    }

    /**
     * Sets the value of the userID property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserID }
     *     
     */
    public void setUserID(UserID value) {
        this.userID = value;
    }

    /**
     * Gets the value of the clientID property.
     * 
     * @return
     *     possible object is
     *     {@link ClientID }
     *     
     */
    public ClientID getClientID() {
        return clientID;
    }

    /**
     * Sets the value of the clientID property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClientID }
     *     
     */
    public void setClientID(ClientID value) {
        this.clientID = value;
    }

    /**
     * Gets the value of the password property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the value of the password property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassword(String value) {
        this.password = value;
    }

    /**
     * Gets the value of the digestBytes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDigestBytes() {
        return digestBytes;
    }

    /**
     * Sets the value of the digestBytes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDigestBytes(String value) {
        this.digestBytes = value;
    }

    /**
     * Gets the value of the digestSchema property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDigestSchema() {
        return digestSchema;
    }

    /**
     * Sets the value of the digestSchema property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDigestSchema(String value) {
        this.digestSchema = value;
    }

    /**
     * Gets the value of the timeToLive property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeToLive() {
        return timeToLive;
    }

    /**
     * Sets the value of the timeToLive property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeToLive(String value) {
        this.timeToLive = value;
    }

    /**
     * Gets the value of the sessionCookie property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSessionCookie() {
        return sessionCookie;
    }

    /**
     * Sets the value of the sessionCookie property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSessionCookie(String value) {
        this.sessionCookie = value;
    }

}
