//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.25 at 05:48:09 PM CEST 
//


package es.rickyepoderi.wbxml.bind.wvcsp;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the es.rickyepoderi.wbxml.wvcsp package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: es.rickyepoderi.wbxml.wvcsp
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SearchResponse }
     * 
     */
    public SearchResponse createSearchResponse() {
        return new SearchResponse();
    }

    /**
     * Create an instance of {@link URLList }
     * 
     */
    public URLList createURLList() {
        return new URLList();
    }

    /**
     * Create an instance of {@link GetGroupMembersRequest }
     * 
     */
    public GetGroupMembersRequest createGetGroupMembersRequest() {
        return new GetGroupMembersRequest();
    }

    /**
     * Create an instance of {@link GroupAuthFunc }
     * 
     */
    public GroupAuthFunc createGroupAuthFunc() {
        return new GroupAuthFunc();
    }

    /**
     * Create an instance of {@link RemoveList }
     * 
     */
    public RemoveList createRemoveList() {
        return new RemoveList();
    }

    /**
     * Create an instance of {@link SupportedCIRMethod }
     * 
     */
    public SupportedCIRMethod createSupportedCIRMethod() {
        return new SupportedCIRMethod();
    }

    /**
     * Create an instance of {@link GETPR }
     * 
     */
    public GETPR createGETPR() {
        return new GETPR();
    }

    /**
     * Create an instance of {@link ClientCapabilityResponse }
     * 
     */
    public ClientCapabilityResponse createClientCapabilityResponse() {
        return new ClientCapabilityResponse();
    }

    /**
     * Create an instance of {@link CancelInviteUserRequest }
     * 
     */
    public CancelInviteUserRequest createCancelInviteUserRequest() {
        return new CancelInviteUserRequest();
    }

    /**
     * Create an instance of {@link FWMSG }
     * 
     */
    public FWMSG createFWMSG() {
        return new FWMSG();
    }

    /**
     * Create an instance of {@link SearchFunc }
     * 
     */
    public SearchFunc createSearchFunc() {
        return new SearchFunc();
    }

    /**
     * Create an instance of {@link GetBlockedListResponse }
     * 
     */
    public GetBlockedListResponse createGetBlockedListResponse() {
        return new GetBlockedListResponse();
    }

    /**
     * Create an instance of {@link DeliveryReportRequest }
     * 
     */
    public DeliveryReportRequest createDeliveryReportRequest() {
        return new DeliveryReportRequest();
    }

    /**
     * Create an instance of {@link ContactList }
     * 
     */
    public ContactList createContactList() {
        return new ContactList();
    }

    /**
     * Create an instance of {@link CreateListRequest }
     * 
     */
    public CreateListRequest createCreateListRequest() {
        return new CreateListRequest();
    }

    /**
     * Create an instance of {@link SearchRequest }
     * 
     */
    public SearchRequest createSearchRequest() {
        return new SearchRequest();
    }

    /**
     * Create an instance of {@link GetGroupPropsRequest }
     * 
     */
    public GetGroupPropsRequest createGetGroupPropsRequest() {
        return new GetGroupPropsRequest();
    }

    /**
     * Create an instance of {@link CCLI }
     * 
     */
    public CCLI createCCLI() {
        return new CCLI();
    }

    /**
     * Create an instance of {@link ClientCapabilityRequest }
     * 
     */
    public ClientCapabilityRequest createClientCapabilityRequest() {
        return new ClientCapabilityRequest();
    }

    /**
     * Create an instance of {@link BLENT }
     * 
     */
    public BLENT createBLENT() {
        return new BLENT();
    }

    /**
     * Create an instance of {@link ServiceRequest }
     * 
     */
    public ServiceRequest createServiceRequest() {
        return new ServiceRequest();
    }

    /**
     * Create an instance of {@link UPDPR }
     * 
     */
    public UPDPR createUPDPR() {
        return new UPDPR();
    }

    /**
     * Create an instance of {@link PresenceNotificationRequest }
     * 
     */
    public PresenceNotificationRequest createPresenceNotificationRequest() {
        return new PresenceNotificationRequest();
    }

    /**
     * Create an instance of {@link LoginResponse }
     * 
     */
    public LoginResponse createLoginResponse() {
        return new LoginResponse();
    }

    /**
     * Create an instance of {@link Status }
     * 
     */
    public Status createStatus() {
        return new Status();
    }

    /**
     * Create an instance of {@link PollingRequest }
     * 
     */
    public PollingRequest createPollingRequest() {
        return new PollingRequest();
    }

    /**
     * Create an instance of {@link PresenceDeliverFunc }
     * 
     */
    public PresenceDeliverFunc createPresenceDeliverFunc() {
        return new PresenceDeliverFunc();
    }

    /**
     * Create an instance of {@link MBRAC }
     * 
     */
    public MBRAC createMBRAC() {
        return new MBRAC();
    }

    /**
     * Create an instance of {@link RemoveGroupMembersRequest }
     * 
     */
    public RemoveGroupMembersRequest createRemoveGroupMembersRequest() {
        return new RemoveGroupMembersRequest();
    }

    /**
     * Create an instance of {@link NickName }
     * 
     */
    public NickName createNickName() {
        return new NickName();
    }

    /**
     * Create an instance of {@link AddGroupMembersRequest }
     * 
     */
    public AddGroupMembersRequest createAddGroupMembersRequest() {
        return new AddGroupMembersRequest();
    }

    /**
     * Create an instance of {@link GroupChangeNotice }
     * 
     */
    public GroupChangeNotice createGroupChangeNotice() {
        return new GroupChangeNotice();
    }

    /**
     * Create an instance of {@link GetSPInfoRequest }
     * 
     */
    public GetSPInfoRequest createGetSPInfoRequest() {
        return new GetSPInfoRequest();
    }

    /**
     * Create an instance of {@link ListManageResponse }
     * 
     */
    public ListManageResponse createListManageResponse() {
        return new ListManageResponse();
    }

    /**
     * Create an instance of {@link GETGP }
     * 
     */
    public GETGP createGETGP() {
        return new GETGP();
    }

    /**
     * Create an instance of {@link UserList }
     * 
     */
    public UserList createUserList() {
        return new UserList();
    }

    /**
     * Create an instance of {@link AddNickList }
     * 
     */
    public AddNickList createAddNickList() {
        return new AddNickList();
    }

    /**
     * Create an instance of {@link RejectListRequest }
     * 
     */
    public RejectListRequest createRejectListRequest() {
        return new RejectListRequest();
    }

    /**
     * Create an instance of {@link REACT }
     * 
     */
    public REACT createREACT() {
        return new REACT();
    }

    /**
     * Create an instance of {@link AcceptedContentType }
     * 
     */
    public AcceptedContentType createAcceptedContentType() {
        return new AcceptedContentType();
    }

    /**
     * Create an instance of {@link GetSPInfoResponse }
     * 
     */
    public GetSPInfoResponse createGetSPInfoResponse() {
        return new GetSPInfoResponse();
    }

    /**
     * Create an instance of {@link OwnProperties }
     * 
     */
    public OwnProperties createOwnProperties() {
        return new OwnProperties();
    }

    /**
     * Create an instance of {@link Session }
     * 
     */
    public Session createSession() {
        return new Session();
    }

    /**
     * Create an instance of {@link SetGroupPropsRequest }
     * 
     */
    public SetGroupPropsRequest createSetGroupPropsRequest() {
        return new SetGroupPropsRequest();
    }

    /**
     * Create an instance of {@link REJCM }
     * 
     */
    public REJCM createREJCM() {
        return new REJCM();
    }

    /**
     * Create an instance of {@link GetWatcherListRequest }
     * 
     */
    public GetWatcherListRequest createGetWatcherListRequest() {
        return new GetWatcherListRequest();
    }

    /**
     * Create an instance of {@link PresenceAuthUser }
     * 
     */
    public PresenceAuthUser createPresenceAuthUser() {
        return new PresenceAuthUser();
    }

    /**
     * Create an instance of {@link DeleteAttributeListRequest }
     * 
     */
    public DeleteAttributeListRequest createDeleteAttributeListRequest() {
        return new DeleteAttributeListRequest();
    }

    /**
     * Create an instance of {@link DefaultAttributeList }
     * 
     */
    public DefaultAttributeList createDefaultAttributeList() {
        return new DefaultAttributeList();
    }

    /**
     * Create an instance of {@link DeleteGroupRequest }
     * 
     */
    public DeleteGroupRequest createDeleteGroupRequest() {
        return new DeleteGroupRequest();
    }

    /**
     * Create an instance of {@link GetPresenceResponse }
     * 
     */
    public GetPresenceResponse createGetPresenceResponse() {
        return new GetPresenceResponse();
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link ForwardMessageRequest }
     * 
     */
    public ForwardMessageRequest createForwardMessageRequest() {
        return new ForwardMessageRequest();
    }

    /**
     * Create an instance of {@link WVCSPMessage }
     * 
     */
    public WVCSPMessage createWVCSPMessage() {
        return new WVCSPMessage();
    }

    /**
     * Create an instance of {@link CAINV }
     * 
     */
    public CAINV createCAINV() {
        return new CAINV();
    }

    /**
     * Create an instance of {@link TransactionContent }
     * 
     */
    public TransactionContent createTransactionContent() {
        return new TransactionContent();
    }

    /**
     * Create an instance of {@link CapabilityList }
     * 
     */
    public CapabilityList createCapabilityList() {
        return new CapabilityList();
    }

    /**
     * Create an instance of {@link DCLI }
     * 
     */
    public DCLI createDCLI() {
        return new DCLI();
    }

    /**
     * Create an instance of {@link ScreenName }
     * 
     */
    public ScreenName createScreenName() {
        return new ScreenName();
    }

    /**
     * Create an instance of {@link SETD }
     * 
     */
    public SETD createSETD() {
        return new SETD();
    }

    /**
     * Create an instance of {@link ServiceFunc }
     * 
     */
    public ServiceFunc createServiceFunc() {
        return new ServiceFunc();
    }

    /**
     * Create an instance of {@link ServiceResponse }
     * 
     */
    public ServiceResponse createServiceResponse() {
        return new ServiceResponse();
    }

    /**
     * Create an instance of {@link DALI }
     * 
     */
    public DALI createDALI() {
        return new DALI();
    }

    /**
     * Create an instance of {@link BlockEntityRequest }
     * 
     */
    public BlockEntityRequest createBlockEntityRequest() {
        return new BlockEntityRequest();
    }

    /**
     * Create an instance of {@link GroupUseFunc }
     * 
     */
    public GroupUseFunc createGroupUseFunc() {
        return new GroupUseFunc();
    }

    /**
     * Create an instance of {@link REJEC }
     * 
     */
    public REJEC createREJEC() {
        return new REJEC();
    }

    /**
     * Create an instance of {@link BlockList }
     * 
     */
    public BlockList createBlockList() {
        return new BlockList();
    }

    /**
     * Create an instance of {@link GETSPI }
     * 
     */
    public GETSPI createGETSPI() {
        return new GETSPI();
    }

    /**
     * Create an instance of {@link RejectListResponse }
     * 
     */
    public RejectListResponse createRejectListResponse() {
        return new RejectListResponse();
    }

    /**
     * Create an instance of {@link ContListFunc }
     * 
     */
    public ContListFunc createContListFunc() {
        return new ContListFunc();
    }

    /**
     * Create an instance of {@link AttListFunc }
     * 
     */
    public AttListFunc createAttListFunc() {
        return new AttListFunc();
    }

    /**
     * Create an instance of {@link GetMessageListRequest }
     * 
     */
    public GetMessageListRequest createGetMessageListRequest() {
        return new GetMessageListRequest();
    }

    /**
     * Create an instance of {@link GroupFeat }
     * 
     */
    public GroupFeat createGroupFeat() {
        return new GroupFeat();
    }

    /**
     * Create an instance of {@link LogoutRequest }
     * 
     */
    public LogoutRequest createLogoutRequest() {
        return new LogoutRequest();
    }

    /**
     * Create an instance of {@link Logo }
     * 
     */
    public Logo createLogo() {
        return new Logo();
    }

    /**
     * Create an instance of {@link MCLS }
     * 
     */
    public MCLS createMCLS() {
        return new MCLS();
    }

    /**
     * Create an instance of {@link SubscribeGroupNoticeRequest }
     * 
     */
    public SubscribeGroupNoticeRequest createSubscribeGroupNoticeRequest() {
        return new SubscribeGroupNoticeRequest();
    }

    /**
     * Create an instance of {@link InviteResponse }
     * 
     */
    public InviteResponse createInviteResponse() {
        return new InviteResponse();
    }

    /**
     * Create an instance of {@link SetDeliveryMethodRequest }
     * 
     */
    public SetDeliveryMethodRequest createSetDeliveryMethodRequest() {
        return new SetDeliveryMethodRequest();
    }

    /**
     * Create an instance of {@link GetAttributeListResponse }
     * 
     */
    public GetAttributeListResponse createGetAttributeListResponse() {
        return new GetAttributeListResponse();
    }

    /**
     * Create an instance of {@link RejectMessageRequest }
     * 
     */
    public RejectMessageRequest createRejectMessageRequest() {
        return new RejectMessageRequest();
    }

    /**
     * Create an instance of {@link AcceptedCharSet }
     * 
     */
    public AcceptedCharSet createAcceptedCharSet() {
        return new AcceptedCharSet();
    }

    /**
     * Create an instance of {@link GRCHN }
     * 
     */
    public GRCHN createGRCHN() {
        return new GRCHN();
    }

    /**
     * Create an instance of {@link IMAuthFunc }
     * 
     */
    public IMAuthFunc createIMAuthFunc() {
        return new IMAuthFunc();
    }

    /**
     * Create an instance of {@link GetListResponse }
     * 
     */
    public GetListResponse createGetListResponse() {
        return new GetListResponse();
    }

    /**
     * Create an instance of {@link PresenceAuthFunc }
     * 
     */
    public PresenceAuthFunc createPresenceAuthFunc() {
        return new PresenceAuthFunc();
    }

    /**
     * Create an instance of {@link IMFeat }
     * 
     */
    public IMFeat createIMFeat() {
        return new IMFeat();
    }

    /**
     * Create an instance of {@link Mod }
     * 
     */
    public Mod createMod() {
        return new Mod();
    }

    /**
     * Create an instance of {@link InviteUserResponse }
     * 
     */
    public InviteUserResponse createInviteUserResponse() {
        return new InviteUserResponse();
    }

    /**
     * Create an instance of {@link ListManageRequest }
     * 
     */
    public ListManageRequest createListManageRequest() {
        return new ListManageRequest();
    }

    /**
     * Create an instance of {@link GCLI }
     * 
     */
    public GCLI createGCLI() {
        return new GCLI();
    }

    /**
     * Create an instance of {@link InviteFunc }
     * 
     */
    public InviteFunc createInviteFunc() {
        return new InviteFunc();
    }

    /**
     * Create an instance of {@link CancelAuthRequest }
     * 
     */
    public CancelAuthRequest createCancelAuthRequest() {
        return new CancelAuthRequest();
    }

    /**
     * Create an instance of {@link LeaveGroupRequest }
     * 
     */
    public LeaveGroupRequest createLeaveGroupRequest() {
        return new LeaveGroupRequest();
    }

    /**
     * Create an instance of {@link GroupID }
     * 
     */
    public GroupID createGroupID() {
        return new GroupID();
    }

    /**
     * Create an instance of {@link IMReceiveFunc }
     * 
     */
    public IMReceiveFunc createIMReceiveFunc() {
        return new IMReceiveFunc();
    }

    /**
     * Create an instance of {@link JoinGroupRequest }
     * 
     */
    public JoinGroupRequest createJoinGroupRequest() {
        return new JoinGroupRequest();
    }

    /**
     * Create an instance of {@link LeaveGroupResponse }
     * 
     */
    public LeaveGroupResponse createLeaveGroupResponse() {
        return new LeaveGroupResponse();
    }

    /**
     * Create an instance of {@link Recipient }
     * 
     */
    public Recipient createRecipient() {
        return new Recipient();
    }

    /**
     * Create an instance of {@link GLBLU }
     * 
     */
    public GLBLU createGLBLU() {
        return new GLBLU();
    }

    /**
     * Create an instance of {@link UnsubscribePresenceRequest }
     * 
     */
    public UnsubscribePresenceRequest createUnsubscribePresenceRequest() {
        return new UnsubscribePresenceRequest();
    }

    /**
     * Create an instance of {@link SupportedBearer }
     * 
     */
    public SupportedBearer createSupportedBearer() {
        return new SupportedBearer();
    }

    /**
     * Create an instance of {@link StopSearchRequest }
     * 
     */
    public StopSearchRequest createStopSearchRequest() {
        return new StopSearchRequest();
    }

    /**
     * Create an instance of {@link Transaction }
     * 
     */
    public Transaction createTransaction() {
        return new Transaction();
    }

    /**
     * Create an instance of {@link SearchResult }
     * 
     */
    public SearchResult createSearchResult() {
        return new SearchResult();
    }

    /**
     * Create an instance of {@link Group }
     * 
     */
    public Group createGroup() {
        return new Group();
    }

    /**
     * Create an instance of {@link MessageInfo }
     * 
     */
    public MessageInfo createMessageInfo() {
        return new MessageInfo();
    }

    /**
     * Create an instance of {@link SessionDescriptor }
     * 
     */
    public SessionDescriptor createSessionDescriptor() {
        return new SessionDescriptor();
    }

    /**
     * Create an instance of {@link AnyContent }
     * 
     */
    public AnyContent createAnyContent() {
        return new AnyContent();
    }

    /**
     * Create an instance of {@link NewMessage }
     * 
     */
    public NewMessage createNewMessage() {
        return new NewMessage();
    }

    /**
     * Create an instance of {@link GetGroupPropsResponse }
     * 
     */
    public GetGroupPropsResponse createGetGroupPropsResponse() {
        return new GetGroupPropsResponse();
    }

    /**
     * Create an instance of {@link SRCH }
     * 
     */
    public SRCH createSRCH() {
        return new SRCH();
    }

    /**
     * Create an instance of {@link Presence }
     * 
     */
    public Presence createPresence() {
        return new Presence();
    }

    /**
     * Create an instance of {@link GetGroupMembersResponse }
     * 
     */
    public GetGroupMembersResponse createGetGroupMembersResponse() {
        return new GetGroupMembersResponse();
    }

    /**
     * Create an instance of {@link EntityList }
     * 
     */
    public EntityList createEntityList() {
        return new EntityList();
    }

    /**
     * Create an instance of {@link PresenceAuthRequest }
     * 
     */
    public PresenceAuthRequest createPresenceAuthRequest() {
        return new PresenceAuthRequest();
    }

    /**
     * Create an instance of {@link Left }
     * 
     */
    public Left createLeft() {
        return new Left();
    }

    /**
     * Create an instance of {@link AcceptedTransferEncoding }
     * 
     */
    public AcceptedTransferEncoding createAcceptedTransferEncoding() {
        return new AcceptedTransferEncoding();
    }

    /**
     * Create an instance of {@link SubscribePresenceRequest }
     * 
     */
    public SubscribePresenceRequest createSubscribePresenceRequest() {
        return new SubscribePresenceRequest();
    }

    /**
     * Create an instance of {@link GroupList }
     * 
     */
    public GroupList createGroupList() {
        return new GroupList();
    }

    /**
     * Create an instance of {@link Property }
     * 
     */
    public Property createProperty() {
        return new Property();
    }

    /**
     * Create an instance of {@link Admin }
     * 
     */
    public Admin createAdmin() {
        return new Admin();
    }

    /**
     * Create an instance of {@link GetAttributeListRequest }
     * 
     */
    public GetAttributeListRequest createGetAttributeListRequest() {
        return new GetAttributeListRequest();
    }

    /**
     * Create an instance of {@link UpdatePresenceRequest }
     * 
     */
    public UpdatePresenceRequest createUpdatePresenceRequest() {
        return new UpdatePresenceRequest();
    }

    /**
     * Create an instance of {@link JoinGroupResponse }
     * 
     */
    public JoinGroupResponse createJoinGroupResponse() {
        return new JoinGroupResponse();
    }

    /**
     * Create an instance of {@link RMVGM }
     * 
     */
    public RMVGM createRMVGM() {
        return new RMVGM();
    }

    /**
     * Create an instance of {@link NOTIF }
     * 
     */
    public NOTIF createNOTIF() {
        return new NOTIF();
    }

    /**
     * Create an instance of {@link PresenceSubList }
     * 
     */
    public PresenceSubList createPresenceSubList() {
        return new PresenceSubList();
    }

    /**
     * Create an instance of {@link SendMessageResponse }
     * 
     */
    public SendMessageResponse createSendMessageResponse() {
        return new SendMessageResponse();
    }

    /**
     * Create an instance of {@link WVCSPFeat }
     * 
     */
    public WVCSPFeat createWVCSPFeat() {
        return new WVCSPFeat();
    }

    /**
     * Create an instance of {@link Functions }
     * 
     */
    public Functions createFunctions() {
        return new Functions();
    }

    /**
     * Create an instance of {@link RemoveNickList }
     * 
     */
    public RemoveNickList createRemoveNickList() {
        return new RemoveNickList();
    }

    /**
     * Create an instance of {@link MessageID }
     * 
     */
    public MessageID createMessageID() {
        return new MessageID();
    }

    /**
     * Create an instance of {@link GetWatcherListResponse }
     * 
     */
    public GetWatcherListResponse createGetWatcherListResponse() {
        return new GetWatcherListResponse();
    }

    /**
     * Create an instance of {@link SendMessageRequest }
     * 
     */
    public SendMessageRequest createSendMessageRequest() {
        return new SendMessageRequest();
    }

    /**
     * Create an instance of {@link GroupMgmtFunc }
     * 
     */
    public GroupMgmtFunc createGroupMgmtFunc() {
        return new GroupMgmtFunc();
    }

    /**
     * Create an instance of {@link KeepAliveResponse }
     * 
     */
    public KeepAliveResponse createKeepAliveResponse() {
        return new KeepAliveResponse();
    }

    /**
     * Create an instance of {@link GetPresenceRequest }
     * 
     */
    public GetPresenceRequest createGetPresenceRequest() {
        return new GetPresenceRequest();
    }

    /**
     * Create an instance of {@link SUBGCN }
     * 
     */
    public SUBGCN createSUBGCN() {
        return new SUBGCN();
    }

    /**
     * Create an instance of {@link FundamentalFeat }
     * 
     */
    public FundamentalFeat createFundamentalFeat() {
        return new FundamentalFeat();
    }

    /**
     * Create an instance of {@link InviteUserRequest }
     * 
     */
    public InviteUserRequest createInviteUserRequest() {
        return new InviteUserRequest();
    }

    /**
     * Create an instance of {@link LoginRequest }
     * 
     */
    public LoginRequest createLoginRequest() {
        return new LoginRequest();
    }

    /**
     * Create an instance of {@link GETWL }
     * 
     */
    public GETWL createGETWL() {
        return new GETWL();
    }

    /**
     * Create an instance of {@link DELGR }
     * 
     */
    public DELGR createDELGR() {
        return new DELGR();
    }

    /**
     * Create an instance of {@link GetMessageResponse }
     * 
     */
    public GetMessageResponse createGetMessageResponse() {
        return new GetMessageResponse();
    }

    /**
     * Create an instance of {@link PresenceFeat }
     * 
     */
    public PresenceFeat createPresenceFeat() {
        return new PresenceFeat();
    }

    /**
     * Create an instance of {@link MessageDelivered }
     * 
     */
    public MessageDelivered createMessageDelivered() {
        return new MessageDelivered();
    }

    /**
     * Create an instance of {@link CreateGroupRequest }
     * 
     */
    public CreateGroupRequest createCreateGroupRequest() {
        return new CreateGroupRequest();
    }

    /**
     * Create an instance of {@link UserID }
     * 
     */
    public UserID createUserID() {
        return new UserID();
    }

    /**
     * Create an instance of {@link AddList }
     * 
     */
    public AddList createAddList() {
        return new AddList();
    }

    /**
     * Create an instance of {@link INVIT }
     * 
     */
    public INVIT createINVIT() {
        return new INVIT();
    }

    /**
     * Create an instance of {@link ContactListProperties }
     * 
     */
    public ContactListProperties createContactListProperties() {
        return new ContactListProperties();
    }

    /**
     * Create an instance of {@link GetMessageListResponse }
     * 
     */
    public GetMessageListResponse createGetMessageListResponse() {
        return new GetMessageListResponse();
    }

    /**
     * Create an instance of {@link DeleteListRequest }
     * 
     */
    public DeleteListRequest createDeleteListRequest() {
        return new DeleteListRequest();
    }

    /**
     * Create an instance of {@link DetailedResult }
     * 
     */
    public DetailedResult createDetailedResult() {
        return new DetailedResult();
    }

    /**
     * Create an instance of {@link GETM }
     * 
     */
    public GETM createGETM() {
        return new GETM();
    }

    /**
     * Create an instance of {@link Disconnect }
     * 
     */
    public Disconnect createDisconnect() {
        return new Disconnect();
    }

    /**
     * Create an instance of {@link WelcomeNote }
     * 
     */
    public WelcomeNote createWelcomeNote() {
        return new WelcomeNote();
    }

    /**
     * Create an instance of {@link MessageNotification }
     * 
     */
    public MessageNotification createMessageNotification() {
        return new MessageNotification();
    }

    /**
     * Create an instance of {@link NickList }
     * 
     */
    public NickList createNickList() {
        return new NickList();
    }

    /**
     * Create an instance of {@link GetMessageRequest }
     * 
     */
    public GetMessageRequest createGetMessageRequest() {
        return new GetMessageRequest();
    }

    /**
     * Create an instance of {@link CreateAttributeListRequest }
     * 
     */
    public CreateAttributeListRequest createCreateAttributeListRequest() {
        return new CreateAttributeListRequest();
    }

    /**
     * Create an instance of {@link MemberAccessRequest }
     * 
     */
    public MemberAccessRequest createMemberAccessRequest() {
        return new MemberAccessRequest();
    }

    /**
     * Create an instance of {@link SubscribeGroupNoticeResponse }
     * 
     */
    public SubscribeGroupNoticeResponse createSubscribeGroupNoticeResponse() {
        return new SubscribeGroupNoticeResponse();
    }

    /**
     * Create an instance of {@link KeepAliveRequest }
     * 
     */
    public KeepAliveRequest createKeepAliveRequest() {
        return new KeepAliveRequest();
    }

    /**
     * Create an instance of {@link CALI }
     * 
     */
    public CALI createCALI() {
        return new CALI();
    }

    /**
     * Create an instance of {@link Users }
     * 
     */
    public Users createUsers() {
        return new Users();
    }

    /**
     * Create an instance of {@link GetListRequest }
     * 
     */
    public GetListRequest createGetListRequest() {
        return new GetListRequest();
    }

    /**
     * Create an instance of {@link GETGM }
     * 
     */
    public GETGM createGETGM() {
        return new GETGM();
    }

    /**
     * Create an instance of {@link Sender }
     * 
     */
    public Sender createSender() {
        return new Sender();
    }

    /**
     * Create an instance of {@link GroupProperties }
     * 
     */
    public GroupProperties createGroupProperties() {
        return new GroupProperties();
    }

    /**
     * Create an instance of {@link AllFunctions }
     * 
     */
    public AllFunctions createAllFunctions() {
        return new AllFunctions();
    }

    /**
     * Create an instance of {@link CancelInviteRequest }
     * 
     */
    public CancelInviteRequest createCancelInviteRequest() {
        return new CancelInviteRequest();
    }

    /**
     * Create an instance of {@link GetBlockedListRequest }
     * 
     */
    public GetBlockedListRequest createGetBlockedListRequest() {
        return new GetBlockedListRequest();
    }

    /**
     * Create an instance of {@link CREAG }
     * 
     */
    public CREAG createCREAG() {
        return new CREAG();
    }

    /**
     * Create an instance of {@link GrantList }
     * 
     */
    public GrantList createGrantList() {
        return new GrantList();
    }

    /**
     * Create an instance of {@link Joined }
     * 
     */
    public Joined createJoined() {
        return new Joined();
    }

    /**
     * Create an instance of {@link STSRC }
     * 
     */
    public STSRC createSTSRC() {
        return new STSRC();
    }

    /**
     * Create an instance of {@link InviteRequest }
     * 
     */
    public InviteRequest createInviteRequest() {
        return new InviteRequest();
    }

    /**
     * Create an instance of {@link IMSendFunc }
     * 
     */
    public IMSendFunc createIMSendFunc() {
        return new IMSendFunc();
    }

    /**
     * Create an instance of {@link SearchPairList }
     * 
     */
    public SearchPairList createSearchPairList() {
        return new SearchPairList();
    }

    /**
     * Create an instance of {@link Result }
     * 
     */
    public Result createResult() {
        return new Result();
    }

    /**
     * Create an instance of {@link ClientID }
     * 
     */
    public ClientID createClientID() {
        return new ClientID();
    }

    /**
     * Create an instance of {@link TransactionDescriptor }
     * 
     */
    public TransactionDescriptor createTransactionDescriptor() {
        return new TransactionDescriptor();
    }

    /**
     * Create an instance of {@link CAAUT }
     * 
     */
    public CAAUT createCAAUT() {
        return new CAAUT();
    }

    /**
     * Create an instance of {@link MDELIV }
     * 
     */
    public MDELIV createMDELIV() {
        return new MDELIV();
    }

    /**
     * Create an instance of {@link GALS }
     * 
     */
    public GALS createGALS() {
        return new GALS();
    }

    /**
     * Create an instance of {@link ADDGM }
     * 
     */
    public ADDGM createADDGM() {
        return new ADDGM();
    }

    /**
     * Create an instance of {@link URL }
     * 
     */
    public URL createURL() {
        return new URL();
    }

    /**
     * Create an instance of {@link NEWM }
     * 
     */
    public NEWM createNEWM() {
        return new NEWM();
    }

    /**
     * Create an instance of {@link GETLM }
     * 
     */
    public GETLM createGETLM() {
        return new GETLM();
    }

    /**
     * Create an instance of {@link SETGP }
     * 
     */
    public SETGP createSETGP() {
        return new SETGP();
    }

}
