//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.25 at 05:48:09 PM CEST 
//


package es.rickyepoderi.wbxml.bind.wvcsp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "contListFunc",
    "presenceAuthFunc",
    "presenceDeliverFunc",
    "attListFunc"
})
@XmlRootElement(name = "PresenceFeat")
public class PresenceFeat {

    @XmlElement(name = "ContListFunc")
    protected ContListFunc contListFunc;
    @XmlElement(name = "PresenceAuthFunc")
    protected PresenceAuthFunc presenceAuthFunc;
    @XmlElement(name = "PresenceDeliverFunc")
    protected PresenceDeliverFunc presenceDeliverFunc;
    @XmlElement(name = "AttListFunc")
    protected AttListFunc attListFunc;

    /**
     * Gets the value of the contListFunc property.
     * 
     * @return
     *     possible object is
     *     {@link ContListFunc }
     *     
     */
    public ContListFunc getContListFunc() {
        return contListFunc;
    }

    /**
     * Sets the value of the contListFunc property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContListFunc }
     *     
     */
    public void setContListFunc(ContListFunc value) {
        this.contListFunc = value;
    }

    /**
     * Gets the value of the presenceAuthFunc property.
     * 
     * @return
     *     possible object is
     *     {@link PresenceAuthFunc }
     *     
     */
    public PresenceAuthFunc getPresenceAuthFunc() {
        return presenceAuthFunc;
    }

    /**
     * Sets the value of the presenceAuthFunc property.
     * 
     * @param value
     *     allowed object is
     *     {@link PresenceAuthFunc }
     *     
     */
    public void setPresenceAuthFunc(PresenceAuthFunc value) {
        this.presenceAuthFunc = value;
    }

    /**
     * Gets the value of the presenceDeliverFunc property.
     * 
     * @return
     *     possible object is
     *     {@link PresenceDeliverFunc }
     *     
     */
    public PresenceDeliverFunc getPresenceDeliverFunc() {
        return presenceDeliverFunc;
    }

    /**
     * Sets the value of the presenceDeliverFunc property.
     * 
     * @param value
     *     allowed object is
     *     {@link PresenceDeliverFunc }
     *     
     */
    public void setPresenceDeliverFunc(PresenceDeliverFunc value) {
        this.presenceDeliverFunc = value;
    }

    /**
     * Gets the value of the attListFunc property.
     * 
     * @return
     *     possible object is
     *     {@link AttListFunc }
     *     
     */
    public AttListFunc getAttListFunc() {
        return attListFunc;
    }

    /**
     * Sets the value of the attListFunc property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttListFunc }
     *     
     */
    public void setAttListFunc(AttListFunc value) {
        this.attListFunc = value;
    }

}
