//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.25 at 05:48:09 PM CEST 
//


package es.rickyepoderi.wbxml.bind.wvcsp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "getwl",
    "react",
    "caaut"
})
@XmlRootElement(name = "PresenceAuthFunc")
public class PresenceAuthFunc {

    @XmlElement(name = "GETWL")
    protected GETWL getwl;
    @XmlElement(name = "REACT")
    protected REACT react;
    @XmlElement(name = "CAAUT")
    protected CAAUT caaut;

    /**
     * Gets the value of the getwl property.
     * 
     * @return
     *     possible object is
     *     {@link GETWL }
     *     
     */
    public GETWL getGETWL() {
        return getwl;
    }

    /**
     * Sets the value of the getwl property.
     * 
     * @param value
     *     allowed object is
     *     {@link GETWL }
     *     
     */
    public void setGETWL(GETWL value) {
        this.getwl = value;
    }

    /**
     * Gets the value of the react property.
     * 
     * @return
     *     possible object is
     *     {@link REACT }
     *     
     */
    public REACT getREACT() {
        return react;
    }

    /**
     * Sets the value of the react property.
     * 
     * @param value
     *     allowed object is
     *     {@link REACT }
     *     
     */
    public void setREACT(REACT value) {
        this.react = value;
    }

    /**
     * Gets the value of the caaut property.
     * 
     * @return
     *     possible object is
     *     {@link CAAUT }
     *     
     */
    public CAAUT getCAAUT() {
        return caaut;
    }

    /**
     * Sets the value of the caaut property.
     * 
     * @param value
     *     allowed object is
     *     {@link CAAUT }
     *     
     */
    public void setCAAUT(CAAUT value) {
        this.caaut = value;
    }

}
