//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.25 at 05:48:09 PM CEST 
//


package es.rickyepoderi.wbxml.bind.wvcsp;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "searchPairList",
    "searchLimit",
    "searchID",
    "searchIndex"
})
@XmlRootElement(name = "Search-Request")
public class SearchRequest {

    @XmlElement(name = "SearchPairList")
    protected List<SearchPairList> searchPairList;
    @XmlElement(name = "SearchLimit")
    protected String searchLimit;
    @XmlElement(name = "SearchID")
    protected String searchID;
    @XmlElement(name = "SearchIndex")
    protected String searchIndex;

    /**
     * Gets the value of the searchPairList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the searchPairList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSearchPairList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SearchPairList }
     * 
     * 
     */
    public List<SearchPairList> getSearchPairList() {
        if (searchPairList == null) {
            searchPairList = new ArrayList<SearchPairList>();
        }
        return this.searchPairList;
    }

    /**
     * Gets the value of the searchLimit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSearchLimit() {
        return searchLimit;
    }

    /**
     * Sets the value of the searchLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSearchLimit(String value) {
        this.searchLimit = value;
    }

    /**
     * Gets the value of the searchID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSearchID() {
        return searchID;
    }

    /**
     * Sets the value of the searchID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSearchID(String value) {
        this.searchID = value;
    }

    /**
     * Gets the value of the searchIndex property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSearchIndex() {
        return searchIndex;
    }

    /**
     * Sets the value of the searchIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSearchIndex(String value) {
        this.searchIndex = value;
    }

}
