//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.25 at 05:48:09 PM CEST 
//


package es.rickyepoderi.wbxml.bind.wvcsp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "searchID",
    "searchFindings",
    "completionFlag",
    "searchIndex",
    "searchResult"
})
@XmlRootElement(name = "Search-Response")
public class SearchResponse {

    @XmlElement(name = "SearchID")
    protected String searchID;
    @XmlElement(name = "SearchFindings", required = true)
    protected String searchFindings;
    @XmlElement(name = "CompletionFlag", required = true)
    protected String completionFlag;
    @XmlElement(name = "SearchIndex", required = true)
    protected String searchIndex;
    @XmlElement(name = "SearchResult")
    protected SearchResult searchResult;

    /**
     * Gets the value of the searchID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSearchID() {
        return searchID;
    }

    /**
     * Sets the value of the searchID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSearchID(String value) {
        this.searchID = value;
    }

    /**
     * Gets the value of the searchFindings property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSearchFindings() {
        return searchFindings;
    }

    /**
     * Sets the value of the searchFindings property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSearchFindings(String value) {
        this.searchFindings = value;
    }

    /**
     * Gets the value of the completionFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompletionFlag() {
        return completionFlag;
    }

    /**
     * Sets the value of the completionFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompletionFlag(String value) {
        this.completionFlag = value;
    }

    /**
     * Gets the value of the searchIndex property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSearchIndex() {
        return searchIndex;
    }

    /**
     * Sets the value of the searchIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSearchIndex(String value) {
        this.searchIndex = value;
    }

    /**
     * Gets the value of the searchResult property.
     * 
     * @return
     *     possible object is
     *     {@link SearchResult }
     *     
     */
    public SearchResult getSearchResult() {
        return searchResult;
    }

    /**
     * Sets the value of the searchResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link SearchResult }
     *     
     */
    public void setSearchResult(SearchResult value) {
        this.searchResult = value;
    }

}
