//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.25 at 05:48:09 PM CEST 
//


package es.rickyepoderi.wbxml.bind.wvcsp;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "statusOrPollingRequestOrLoginRequestOrLoginResponseOrServiceRequestOrServiceResponseOrClientCapabilityRequestOrClientCapabilityResponseOrLogoutRequestOrDisconnectOrKeepAliveRequestOrKeepAliveResponseOrGetSPInfoRequestOrGetSPInfoResponseOrSearchRequestOrSearchResponseOrStopSearchRequestOrInviteRequestOrInviteResponseOrInviteUserRequestOrInviteUserResponseOrCancelInviteRequestOrCancelInviteUserRequestOrSubscribePresenceRequestOrUnsubscribePresenceRequestOrPresenceNotificationRequestOrGetWatcherListRequestOrGetWatcherListResponseOrGetPresenceRequestOrGetPresenceResponseOrPresenceAuthRequestOrPresenceAuthUserOrCancelAuthRequestOrUpdatePresenceRequestOrSendMessageRequestOrSendMessageResponseOrSetDeliveryMethodRequestOrGetMessageListRequestOrGetMessageListResponseOrRejectMessageRequestOrMessageNotificationOrGetMessageRequestOrGetMessageResponseOrNewMessageOrMessageDeliveredOrDeliveryReportRequestOrForwardMessageRequestOrGetBlockedListRequestOrGetBlockedListResponseOrBlockEntityRequestOrGetListRequestOrGetListResponseOrCreateListRequestOrDeleteListRequestOrListManageRequestOrListManageResponseOrCreateAttributeListRequestOrDeleteAttributeListRequestOrGetAttributeListRequestOrGetAttributeListResponseOrCreateGroupRequestOrDeleteGroupRequestOrJoinGroupRequestOrJoinGroupResponseOrLeaveGroupRequestOrLeaveGroupResponseOrGetGroupMembersRequestOrGetGroupMembersResponseOrAddGroupMembersRequestOrRemoveGroupMembersRequestOrMemberAccessRequestOrGetGroupPropsRequestOrGetGroupPropsResponseOrSetGroupPropsRequestOrRejectListRequestOrRejectListResponseOrSubscribeGroupNoticeRequestOrSubscribeGroupNoticeResponseOrGroupChangeNotice"
})
@XmlRootElement(name = "TransactionContent")
public class TransactionContent {

    @XmlAttribute
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String xmlns;
    @XmlElements({
        @XmlElement(name = "Status", required = true, type = Status.class),
        @XmlElement(name = "Polling-Request", required = true, type = PollingRequest.class),
        @XmlElement(name = "Login-Request", required = true, type = LoginRequest.class),
        @XmlElement(name = "Login-Response", required = true, type = LoginResponse.class),
        @XmlElement(name = "Service-Request", required = true, type = ServiceRequest.class),
        @XmlElement(name = "Service-Response", required = true, type = ServiceResponse.class),
        @XmlElement(name = "ClientCapability-Request", required = true, type = ClientCapabilityRequest.class),
        @XmlElement(name = "ClientCapability-Response", required = true, type = ClientCapabilityResponse.class),
        @XmlElement(name = "Logout-Request", required = true, type = LogoutRequest.class),
        @XmlElement(name = "Disconnect", required = true, type = Disconnect.class),
        @XmlElement(name = "KeepAlive-Request", required = true, type = KeepAliveRequest.class),
        @XmlElement(name = "KeepAlive-Response", required = true, type = KeepAliveResponse.class),
        @XmlElement(name = "GetSPInfo-Request", required = true, type = GetSPInfoRequest.class),
        @XmlElement(name = "GetSPInfo-Response", required = true, type = GetSPInfoResponse.class),
        @XmlElement(name = "Search-Request", required = true, type = SearchRequest.class),
        @XmlElement(name = "Search-Response", required = true, type = SearchResponse.class),
        @XmlElement(name = "StopSearch-Request", required = true, type = StopSearchRequest.class),
        @XmlElement(name = "Invite-Request", required = true, type = InviteRequest.class),
        @XmlElement(name = "Invite-Response", required = true, type = InviteResponse.class),
        @XmlElement(name = "InviteUser-Request", required = true, type = InviteUserRequest.class),
        @XmlElement(name = "InviteUser-Response", required = true, type = InviteUserResponse.class),
        @XmlElement(name = "CancelInvite-Request", required = true, type = CancelInviteRequest.class),
        @XmlElement(name = "CancelInviteUser-Request", required = true, type = CancelInviteUserRequest.class),
        @XmlElement(name = "SubscribePresence-Request", required = true, type = SubscribePresenceRequest.class),
        @XmlElement(name = "UnsubscribePresence-Request", required = true, type = UnsubscribePresenceRequest.class),
        @XmlElement(name = "PresenceNotification-Request", required = true, type = PresenceNotificationRequest.class),
        @XmlElement(name = "GetWatcherList-Request", required = true, type = GetWatcherListRequest.class),
        @XmlElement(name = "GetWatcherList-Response", required = true, type = GetWatcherListResponse.class),
        @XmlElement(name = "GetPresence-Request", required = true, type = GetPresenceRequest.class),
        @XmlElement(name = "GetPresence-Response", required = true, type = GetPresenceResponse.class),
        @XmlElement(name = "PresenceAuth-Request", required = true, type = PresenceAuthRequest.class),
        @XmlElement(name = "PresenceAuth-User", required = true, type = PresenceAuthUser.class),
        @XmlElement(name = "CancelAuth-Request", required = true, type = CancelAuthRequest.class),
        @XmlElement(name = "UpdatePresence-Request", required = true, type = UpdatePresenceRequest.class),
        @XmlElement(name = "SendMessage-Request", required = true, type = SendMessageRequest.class),
        @XmlElement(name = "SendMessage-Response", required = true, type = SendMessageResponse.class),
        @XmlElement(name = "SetDeliveryMethod-Request", required = true, type = SetDeliveryMethodRequest.class),
        @XmlElement(name = "GetMessageList-Request", required = true, type = GetMessageListRequest.class),
        @XmlElement(name = "GetMessageList-Response", required = true, type = GetMessageListResponse.class),
        @XmlElement(name = "RejectMessage-Request", required = true, type = RejectMessageRequest.class),
        @XmlElement(name = "MessageNotification", required = true, type = MessageNotification.class),
        @XmlElement(name = "GetMessage-Request", required = true, type = GetMessageRequest.class),
        @XmlElement(name = "GetMessage-Response", required = true, type = GetMessageResponse.class),
        @XmlElement(name = "NewMessage", required = true, type = NewMessage.class),
        @XmlElement(name = "MessageDelivered", required = true, type = MessageDelivered.class),
        @XmlElement(name = "DeliveryReport-Request", required = true, type = DeliveryReportRequest.class),
        @XmlElement(name = "ForwardMessage-Request", required = true, type = ForwardMessageRequest.class),
        @XmlElement(name = "GetBlockedList-Request", required = true, type = GetBlockedListRequest.class),
        @XmlElement(name = "GetBlockedList-Response", required = true, type = GetBlockedListResponse.class),
        @XmlElement(name = "BlockEntity-Request", required = true, type = BlockEntityRequest.class),
        @XmlElement(name = "GetList-Request", required = true, type = GetListRequest.class),
        @XmlElement(name = "GetList-Response", required = true, type = GetListResponse.class),
        @XmlElement(name = "CreateList-Request", required = true, type = CreateListRequest.class),
        @XmlElement(name = "DeleteList-Request", required = true, type = DeleteListRequest.class),
        @XmlElement(name = "ListManage-Request", required = true, type = ListManageRequest.class),
        @XmlElement(name = "ListManage-Response", required = true, type = ListManageResponse.class),
        @XmlElement(name = "CreateAttributeList-Request", required = true, type = CreateAttributeListRequest.class),
        @XmlElement(name = "DeleteAttributeList-Request", required = true, type = DeleteAttributeListRequest.class),
        @XmlElement(name = "GetAttributeList-Request", required = true, type = GetAttributeListRequest.class),
        @XmlElement(name = "GetAttributeList-Response", required = true, type = GetAttributeListResponse.class),
        @XmlElement(name = "CreateGroup-Request", required = true, type = CreateGroupRequest.class),
        @XmlElement(name = "DeleteGroup-Request", required = true, type = DeleteGroupRequest.class),
        @XmlElement(name = "JoinGroup-Request", required = true, type = JoinGroupRequest.class),
        @XmlElement(name = "JoinGroup-Response", required = true, type = JoinGroupResponse.class),
        @XmlElement(name = "LeaveGroup-Request", required = true, type = LeaveGroupRequest.class),
        @XmlElement(name = "LeaveGroup-Response", required = true, type = LeaveGroupResponse.class),
        @XmlElement(name = "GetGroupMembers-Request", required = true, type = GetGroupMembersRequest.class),
        @XmlElement(name = "GetGroupMembers-Response", required = true, type = GetGroupMembersResponse.class),
        @XmlElement(name = "AddGroupMembers-Request", required = true, type = AddGroupMembersRequest.class),
        @XmlElement(name = "RemoveGroupMembers-Request", required = true, type = RemoveGroupMembersRequest.class),
        @XmlElement(name = "MemberAccess-Request", required = true, type = MemberAccessRequest.class),
        @XmlElement(name = "GetGroupProps-Request", required = true, type = GetGroupPropsRequest.class),
        @XmlElement(name = "GetGroupProps-Response", required = true, type = GetGroupPropsResponse.class),
        @XmlElement(name = "SetGroupProps-Request", required = true, type = SetGroupPropsRequest.class),
        @XmlElement(name = "RejectList-Request", required = true, type = RejectListRequest.class),
        @XmlElement(name = "RejectList-Response", required = true, type = RejectListResponse.class),
        @XmlElement(name = "SubscribeGroupNotice-Request", required = true, type = SubscribeGroupNoticeRequest.class),
        @XmlElement(name = "SubscribeGroupNotice-Response", required = true, type = SubscribeGroupNoticeResponse.class),
        @XmlElement(name = "GroupChangeNotice", required = true, type = GroupChangeNotice.class)
    })
    protected List<Object> statusOrPollingRequestOrLoginRequestOrLoginResponseOrServiceRequestOrServiceResponseOrClientCapabilityRequestOrClientCapabilityResponseOrLogoutRequestOrDisconnectOrKeepAliveRequestOrKeepAliveResponseOrGetSPInfoRequestOrGetSPInfoResponseOrSearchRequestOrSearchResponseOrStopSearchRequestOrInviteRequestOrInviteResponseOrInviteUserRequestOrInviteUserResponseOrCancelInviteRequestOrCancelInviteUserRequestOrSubscribePresenceRequestOrUnsubscribePresenceRequestOrPresenceNotificationRequestOrGetWatcherListRequestOrGetWatcherListResponseOrGetPresenceRequestOrGetPresenceResponseOrPresenceAuthRequestOrPresenceAuthUserOrCancelAuthRequestOrUpdatePresenceRequestOrSendMessageRequestOrSendMessageResponseOrSetDeliveryMethodRequestOrGetMessageListRequestOrGetMessageListResponseOrRejectMessageRequestOrMessageNotificationOrGetMessageRequestOrGetMessageResponseOrNewMessageOrMessageDeliveredOrDeliveryReportRequestOrForwardMessageRequestOrGetBlockedListRequestOrGetBlockedListResponseOrBlockEntityRequestOrGetListRequestOrGetListResponseOrCreateListRequestOrDeleteListRequestOrListManageRequestOrListManageResponseOrCreateAttributeListRequestOrDeleteAttributeListRequestOrGetAttributeListRequestOrGetAttributeListResponseOrCreateGroupRequestOrDeleteGroupRequestOrJoinGroupRequestOrJoinGroupResponseOrLeaveGroupRequestOrLeaveGroupResponseOrGetGroupMembersRequestOrGetGroupMembersResponseOrAddGroupMembersRequestOrRemoveGroupMembersRequestOrMemberAccessRequestOrGetGroupPropsRequestOrGetGroupPropsResponseOrSetGroupPropsRequestOrRejectListRequestOrRejectListResponseOrSubscribeGroupNoticeRequestOrSubscribeGroupNoticeResponseOrGroupChangeNotice;

    /**
     * Gets the value of the xmlns property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXmlns() {
        return xmlns;
    }

    /**
     * Sets the value of the xmlns property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXmlns(String value) {
        this.xmlns = value;
    }

    /**
     * Gets the value of the statusOrPollingRequestOrLoginRequestOrLoginResponseOrServiceRequestOrServiceResponseOrClientCapabilityRequestOrClientCapabilityResponseOrLogoutRequestOrDisconnectOrKeepAliveRequestOrKeepAliveResponseOrGetSPInfoRequestOrGetSPInfoResponseOrSearchRequestOrSearchResponseOrStopSearchRequestOrInviteRequestOrInviteResponseOrInviteUserRequestOrInviteUserResponseOrCancelInviteRequestOrCancelInviteUserRequestOrSubscribePresenceRequestOrUnsubscribePresenceRequestOrPresenceNotificationRequestOrGetWatcherListRequestOrGetWatcherListResponseOrGetPresenceRequestOrGetPresenceResponseOrPresenceAuthRequestOrPresenceAuthUserOrCancelAuthRequestOrUpdatePresenceRequestOrSendMessageRequestOrSendMessageResponseOrSetDeliveryMethodRequestOrGetMessageListRequestOrGetMessageListResponseOrRejectMessageRequestOrMessageNotificationOrGetMessageRequestOrGetMessageResponseOrNewMessageOrMessageDeliveredOrDeliveryReportRequestOrForwardMessageRequestOrGetBlockedListRequestOrGetBlockedListResponseOrBlockEntityRequestOrGetListRequestOrGetListResponseOrCreateListRequestOrDeleteListRequestOrListManageRequestOrListManageResponseOrCreateAttributeListRequestOrDeleteAttributeListRequestOrGetAttributeListRequestOrGetAttributeListResponseOrCreateGroupRequestOrDeleteGroupRequestOrJoinGroupRequestOrJoinGroupResponseOrLeaveGroupRequestOrLeaveGroupResponseOrGetGroupMembersRequestOrGetGroupMembersResponseOrAddGroupMembersRequestOrRemoveGroupMembersRequestOrMemberAccessRequestOrGetGroupPropsRequestOrGetGroupPropsResponseOrSetGroupPropsRequestOrRejectListRequestOrRejectListResponseOrSubscribeGroupNoticeRequestOrSubscribeGroupNoticeResponseOrGroupChangeNotice property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the statusOrPollingRequestOrLoginRequestOrLoginResponseOrServiceRequestOrServiceResponseOrClientCapabilityRequestOrClientCapabilityResponseOrLogoutRequestOrDisconnectOrKeepAliveRequestOrKeepAliveResponseOrGetSPInfoRequestOrGetSPInfoResponseOrSearchRequestOrSearchResponseOrStopSearchRequestOrInviteRequestOrInviteResponseOrInviteUserRequestOrInviteUserResponseOrCancelInviteRequestOrCancelInviteUserRequestOrSubscribePresenceRequestOrUnsubscribePresenceRequestOrPresenceNotificationRequestOrGetWatcherListRequestOrGetWatcherListResponseOrGetPresenceRequestOrGetPresenceResponseOrPresenceAuthRequestOrPresenceAuthUserOrCancelAuthRequestOrUpdatePresenceRequestOrSendMessageRequestOrSendMessageResponseOrSetDeliveryMethodRequestOrGetMessageListRequestOrGetMessageListResponseOrRejectMessageRequestOrMessageNotificationOrGetMessageRequestOrGetMessageResponseOrNewMessageOrMessageDeliveredOrDeliveryReportRequestOrForwardMessageRequestOrGetBlockedListRequestOrGetBlockedListResponseOrBlockEntityRequestOrGetListRequestOrGetListResponseOrCreateListRequestOrDeleteListRequestOrListManageRequestOrListManageResponseOrCreateAttributeListRequestOrDeleteAttributeListRequestOrGetAttributeListRequestOrGetAttributeListResponseOrCreateGroupRequestOrDeleteGroupRequestOrJoinGroupRequestOrJoinGroupResponseOrLeaveGroupRequestOrLeaveGroupResponseOrGetGroupMembersRequestOrGetGroupMembersResponseOrAddGroupMembersRequestOrRemoveGroupMembersRequestOrMemberAccessRequestOrGetGroupPropsRequestOrGetGroupPropsResponseOrSetGroupPropsRequestOrRejectListRequestOrRejectListResponseOrSubscribeGroupNoticeRequestOrSubscribeGroupNoticeResponseOrGroupChangeNotice property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStatusOrPollingRequestOrLoginRequestOrLoginResponseOrServiceRequestOrServiceResponseOrClientCapabilityRequestOrClientCapabilityResponseOrLogoutRequestOrDisconnectOrKeepAliveRequestOrKeepAliveResponseOrGetSPInfoRequestOrGetSPInfoResponseOrSearchRequestOrSearchResponseOrStopSearchRequestOrInviteRequestOrInviteResponseOrInviteUserRequestOrInviteUserResponseOrCancelInviteRequestOrCancelInviteUserRequestOrSubscribePresenceRequestOrUnsubscribePresenceRequestOrPresenceNotificationRequestOrGetWatcherListRequestOrGetWatcherListResponseOrGetPresenceRequestOrGetPresenceResponseOrPresenceAuthRequestOrPresenceAuthUserOrCancelAuthRequestOrUpdatePresenceRequestOrSendMessageRequestOrSendMessageResponseOrSetDeliveryMethodRequestOrGetMessageListRequestOrGetMessageListResponseOrRejectMessageRequestOrMessageNotificationOrGetMessageRequestOrGetMessageResponseOrNewMessageOrMessageDeliveredOrDeliveryReportRequestOrForwardMessageRequestOrGetBlockedListRequestOrGetBlockedListResponseOrBlockEntityRequestOrGetListRequestOrGetListResponseOrCreateListRequestOrDeleteListRequestOrListManageRequestOrListManageResponseOrCreateAttributeListRequestOrDeleteAttributeListRequestOrGetAttributeListRequestOrGetAttributeListResponseOrCreateGroupRequestOrDeleteGroupRequestOrJoinGroupRequestOrJoinGroupResponseOrLeaveGroupRequestOrLeaveGroupResponseOrGetGroupMembersRequestOrGetGroupMembersResponseOrAddGroupMembersRequestOrRemoveGroupMembersRequestOrMemberAccessRequestOrGetGroupPropsRequestOrGetGroupPropsResponseOrSetGroupPropsRequestOrRejectListRequestOrRejectListResponseOrSubscribeGroupNoticeRequestOrSubscribeGroupNoticeResponseOrGroupChangeNotice().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Status }
     * {@link PollingRequest }
     * {@link LoginRequest }
     * {@link LoginResponse }
     * {@link ServiceRequest }
     * {@link ServiceResponse }
     * {@link ClientCapabilityRequest }
     * {@link ClientCapabilityResponse }
     * {@link LogoutRequest }
     * {@link Disconnect }
     * {@link KeepAliveRequest }
     * {@link KeepAliveResponse }
     * {@link GetSPInfoRequest }
     * {@link GetSPInfoResponse }
     * {@link SearchRequest }
     * {@link SearchResponse }
     * {@link StopSearchRequest }
     * {@link InviteRequest }
     * {@link InviteResponse }
     * {@link InviteUserRequest }
     * {@link InviteUserResponse }
     * {@link CancelInviteRequest }
     * {@link CancelInviteUserRequest }
     * {@link SubscribePresenceRequest }
     * {@link UnsubscribePresenceRequest }
     * {@link PresenceNotificationRequest }
     * {@link GetWatcherListRequest }
     * {@link GetWatcherListResponse }
     * {@link GetPresenceRequest }
     * {@link GetPresenceResponse }
     * {@link PresenceAuthRequest }
     * {@link PresenceAuthUser }
     * {@link CancelAuthRequest }
     * {@link UpdatePresenceRequest }
     * {@link SendMessageRequest }
     * {@link SendMessageResponse }
     * {@link SetDeliveryMethodRequest }
     * {@link GetMessageListRequest }
     * {@link GetMessageListResponse }
     * {@link RejectMessageRequest }
     * {@link MessageNotification }
     * {@link GetMessageRequest }
     * {@link GetMessageResponse }
     * {@link NewMessage }
     * {@link MessageDelivered }
     * {@link DeliveryReportRequest }
     * {@link ForwardMessageRequest }
     * {@link GetBlockedListRequest }
     * {@link GetBlockedListResponse }
     * {@link BlockEntityRequest }
     * {@link GetListRequest }
     * {@link GetListResponse }
     * {@link CreateListRequest }
     * {@link DeleteListRequest }
     * {@link ListManageRequest }
     * {@link ListManageResponse }
     * {@link CreateAttributeListRequest }
     * {@link DeleteAttributeListRequest }
     * {@link GetAttributeListRequest }
     * {@link GetAttributeListResponse }
     * {@link CreateGroupRequest }
     * {@link DeleteGroupRequest }
     * {@link JoinGroupRequest }
     * {@link JoinGroupResponse }
     * {@link LeaveGroupRequest }
     * {@link LeaveGroupResponse }
     * {@link GetGroupMembersRequest }
     * {@link GetGroupMembersResponse }
     * {@link AddGroupMembersRequest }
     * {@link RemoveGroupMembersRequest }
     * {@link MemberAccessRequest }
     * {@link GetGroupPropsRequest }
     * {@link GetGroupPropsResponse }
     * {@link SetGroupPropsRequest }
     * {@link RejectListRequest }
     * {@link RejectListResponse }
     * {@link SubscribeGroupNoticeRequest }
     * {@link SubscribeGroupNoticeResponse }
     * {@link GroupChangeNotice }
     * 
     * 
     */
    public List<Object> getStatusOrPollingRequestOrLoginRequestOrLoginResponseOrServiceRequestOrServiceResponseOrClientCapabilityRequestOrClientCapabilityResponseOrLogoutRequestOrDisconnectOrKeepAliveRequestOrKeepAliveResponseOrGetSPInfoRequestOrGetSPInfoResponseOrSearchRequestOrSearchResponseOrStopSearchRequestOrInviteRequestOrInviteResponseOrInviteUserRequestOrInviteUserResponseOrCancelInviteRequestOrCancelInviteUserRequestOrSubscribePresenceRequestOrUnsubscribePresenceRequestOrPresenceNotificationRequestOrGetWatcherListRequestOrGetWatcherListResponseOrGetPresenceRequestOrGetPresenceResponseOrPresenceAuthRequestOrPresenceAuthUserOrCancelAuthRequestOrUpdatePresenceRequestOrSendMessageRequestOrSendMessageResponseOrSetDeliveryMethodRequestOrGetMessageListRequestOrGetMessageListResponseOrRejectMessageRequestOrMessageNotificationOrGetMessageRequestOrGetMessageResponseOrNewMessageOrMessageDeliveredOrDeliveryReportRequestOrForwardMessageRequestOrGetBlockedListRequestOrGetBlockedListResponseOrBlockEntityRequestOrGetListRequestOrGetListResponseOrCreateListRequestOrDeleteListRequestOrListManageRequestOrListManageResponseOrCreateAttributeListRequestOrDeleteAttributeListRequestOrGetAttributeListRequestOrGetAttributeListResponseOrCreateGroupRequestOrDeleteGroupRequestOrJoinGroupRequestOrJoinGroupResponseOrLeaveGroupRequestOrLeaveGroupResponseOrGetGroupMembersRequestOrGetGroupMembersResponseOrAddGroupMembersRequestOrRemoveGroupMembersRequestOrMemberAccessRequestOrGetGroupPropsRequestOrGetGroupPropsResponseOrSetGroupPropsRequestOrRejectListRequestOrRejectListResponseOrSubscribeGroupNoticeRequestOrSubscribeGroupNoticeResponseOrGroupChangeNotice() {
        if (statusOrPollingRequestOrLoginRequestOrLoginResponseOrServiceRequestOrServiceResponseOrClientCapabilityRequestOrClientCapabilityResponseOrLogoutRequestOrDisconnectOrKeepAliveRequestOrKeepAliveResponseOrGetSPInfoRequestOrGetSPInfoResponseOrSearchRequestOrSearchResponseOrStopSearchRequestOrInviteRequestOrInviteResponseOrInviteUserRequestOrInviteUserResponseOrCancelInviteRequestOrCancelInviteUserRequestOrSubscribePresenceRequestOrUnsubscribePresenceRequestOrPresenceNotificationRequestOrGetWatcherListRequestOrGetWatcherListResponseOrGetPresenceRequestOrGetPresenceResponseOrPresenceAuthRequestOrPresenceAuthUserOrCancelAuthRequestOrUpdatePresenceRequestOrSendMessageRequestOrSendMessageResponseOrSetDeliveryMethodRequestOrGetMessageListRequestOrGetMessageListResponseOrRejectMessageRequestOrMessageNotificationOrGetMessageRequestOrGetMessageResponseOrNewMessageOrMessageDeliveredOrDeliveryReportRequestOrForwardMessageRequestOrGetBlockedListRequestOrGetBlockedListResponseOrBlockEntityRequestOrGetListRequestOrGetListResponseOrCreateListRequestOrDeleteListRequestOrListManageRequestOrListManageResponseOrCreateAttributeListRequestOrDeleteAttributeListRequestOrGetAttributeListRequestOrGetAttributeListResponseOrCreateGroupRequestOrDeleteGroupRequestOrJoinGroupRequestOrJoinGroupResponseOrLeaveGroupRequestOrLeaveGroupResponseOrGetGroupMembersRequestOrGetGroupMembersResponseOrAddGroupMembersRequestOrRemoveGroupMembersRequestOrMemberAccessRequestOrGetGroupPropsRequestOrGetGroupPropsResponseOrSetGroupPropsRequestOrRejectListRequestOrRejectListResponseOrSubscribeGroupNoticeRequestOrSubscribeGroupNoticeResponseOrGroupChangeNotice == null) {
            statusOrPollingRequestOrLoginRequestOrLoginResponseOrServiceRequestOrServiceResponseOrClientCapabilityRequestOrClientCapabilityResponseOrLogoutRequestOrDisconnectOrKeepAliveRequestOrKeepAliveResponseOrGetSPInfoRequestOrGetSPInfoResponseOrSearchRequestOrSearchResponseOrStopSearchRequestOrInviteRequestOrInviteResponseOrInviteUserRequestOrInviteUserResponseOrCancelInviteRequestOrCancelInviteUserRequestOrSubscribePresenceRequestOrUnsubscribePresenceRequestOrPresenceNotificationRequestOrGetWatcherListRequestOrGetWatcherListResponseOrGetPresenceRequestOrGetPresenceResponseOrPresenceAuthRequestOrPresenceAuthUserOrCancelAuthRequestOrUpdatePresenceRequestOrSendMessageRequestOrSendMessageResponseOrSetDeliveryMethodRequestOrGetMessageListRequestOrGetMessageListResponseOrRejectMessageRequestOrMessageNotificationOrGetMessageRequestOrGetMessageResponseOrNewMessageOrMessageDeliveredOrDeliveryReportRequestOrForwardMessageRequestOrGetBlockedListRequestOrGetBlockedListResponseOrBlockEntityRequestOrGetListRequestOrGetListResponseOrCreateListRequestOrDeleteListRequestOrListManageRequestOrListManageResponseOrCreateAttributeListRequestOrDeleteAttributeListRequestOrGetAttributeListRequestOrGetAttributeListResponseOrCreateGroupRequestOrDeleteGroupRequestOrJoinGroupRequestOrJoinGroupResponseOrLeaveGroupRequestOrLeaveGroupResponseOrGetGroupMembersRequestOrGetGroupMembersResponseOrAddGroupMembersRequestOrRemoveGroupMembersRequestOrMemberAccessRequestOrGetGroupPropsRequestOrGetGroupPropsResponseOrSetGroupPropsRequestOrRejectListRequestOrRejectListResponseOrSubscribeGroupNoticeRequestOrSubscribeGroupNoticeResponseOrGroupChangeNotice = new ArrayList<Object>();
        }
        return this.statusOrPollingRequestOrLoginRequestOrLoginResponseOrServiceRequestOrServiceResponseOrClientCapabilityRequestOrClientCapabilityResponseOrLogoutRequestOrDisconnectOrKeepAliveRequestOrKeepAliveResponseOrGetSPInfoRequestOrGetSPInfoResponseOrSearchRequestOrSearchResponseOrStopSearchRequestOrInviteRequestOrInviteResponseOrInviteUserRequestOrInviteUserResponseOrCancelInviteRequestOrCancelInviteUserRequestOrSubscribePresenceRequestOrUnsubscribePresenceRequestOrPresenceNotificationRequestOrGetWatcherListRequestOrGetWatcherListResponseOrGetPresenceRequestOrGetPresenceResponseOrPresenceAuthRequestOrPresenceAuthUserOrCancelAuthRequestOrUpdatePresenceRequestOrSendMessageRequestOrSendMessageResponseOrSetDeliveryMethodRequestOrGetMessageListRequestOrGetMessageListResponseOrRejectMessageRequestOrMessageNotificationOrGetMessageRequestOrGetMessageResponseOrNewMessageOrMessageDeliveredOrDeliveryReportRequestOrForwardMessageRequestOrGetBlockedListRequestOrGetBlockedListResponseOrBlockEntityRequestOrGetListRequestOrGetListResponseOrCreateListRequestOrDeleteListRequestOrListManageRequestOrListManageResponseOrCreateAttributeListRequestOrDeleteAttributeListRequestOrGetAttributeListRequestOrGetAttributeListResponseOrCreateGroupRequestOrDeleteGroupRequestOrJoinGroupRequestOrJoinGroupResponseOrLeaveGroupRequestOrLeaveGroupResponseOrGetGroupMembersRequestOrGetGroupMembersResponseOrAddGroupMembersRequestOrRemoveGroupMembersRequestOrMemberAccessRequestOrGetGroupPropsRequestOrGetGroupPropsResponseOrSetGroupPropsRequestOrRejectListRequestOrRejectListResponseOrSubscribeGroupNoticeRequestOrSubscribeGroupNoticeResponseOrGroupChangeNotice;
    }

}
