//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.25 at 05:48:09 PM CEST 
//


package es.rickyepoderi.wbxml.bind.wvcsp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "transactionDescriptor",
    "transactionContent"
})
@XmlRootElement(name = "Transaction")
public class Transaction {

    @XmlElement(name = "TransactionDescriptor", required = true)
    protected TransactionDescriptor transactionDescriptor;
    @XmlElement(name = "TransactionContent", required = true)
    protected TransactionContent transactionContent;

    /**
     * Gets the value of the transactionDescriptor property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionDescriptor }
     *     
     */
    public TransactionDescriptor getTransactionDescriptor() {
        return transactionDescriptor;
    }

    /**
     * Sets the value of the transactionDescriptor property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionDescriptor }
     *     
     */
    public void setTransactionDescriptor(TransactionDescriptor value) {
        this.transactionDescriptor = value;
    }

    /**
     * Gets the value of the transactionContent property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionContent }
     *     
     */
    public TransactionContent getTransactionContent() {
        return transactionContent;
    }

    /**
     * Sets the value of the transactionContent property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionContent }
     *     
     */
    public void setTransactionContent(TransactionContent value) {
        this.transactionContent = value;
    }

}
