//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.25 at 05:48:09 PM CEST 
//


package es.rickyepoderi.wbxml.bind.wvcsp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "presenceSubList"
})
@XmlRootElement(name = "UpdatePresence-Request")
public class UpdatePresenceRequest {

    @XmlElement(name = "PresenceSubList", required = true)
    protected PresenceSubList presenceSubList;

    /**
     * Gets the value of the presenceSubList property.
     * 
     * @return
     *     possible object is
     *     {@link PresenceSubList }
     *     
     */
    public PresenceSubList getPresenceSubList() {
        return presenceSubList;
    }

    /**
     * Sets the value of the presenceSubList property.
     * 
     * @param value
     *     allowed object is
     *     {@link PresenceSubList }
     *     
     */
    public void setPresenceSubList(PresenceSubList value) {
        this.presenceSubList = value;
    }

}
