//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.25 at 05:48:09 PM CEST 
//


package es.rickyepoderi.wbxml.bind.wvcsp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fundamentalFeat",
    "presenceFeat",
    "imFeat",
    "groupFeat"
})
@XmlRootElement(name = "WVCSPFeat")
public class WVCSPFeat {

    @XmlElement(name = "FundamentalFeat")
    protected FundamentalFeat fundamentalFeat;
    @XmlElement(name = "PresenceFeat")
    protected PresenceFeat presenceFeat;
    @XmlElement(name = "IMFeat")
    protected IMFeat imFeat;
    @XmlElement(name = "GroupFeat")
    protected GroupFeat groupFeat;

    /**
     * Gets the value of the fundamentalFeat property.
     * 
     * @return
     *     possible object is
     *     {@link FundamentalFeat }
     *     
     */
    public FundamentalFeat getFundamentalFeat() {
        return fundamentalFeat;
    }

    /**
     * Sets the value of the fundamentalFeat property.
     * 
     * @param value
     *     allowed object is
     *     {@link FundamentalFeat }
     *     
     */
    public void setFundamentalFeat(FundamentalFeat value) {
        this.fundamentalFeat = value;
    }

    /**
     * Gets the value of the presenceFeat property.
     * 
     * @return
     *     possible object is
     *     {@link PresenceFeat }
     *     
     */
    public PresenceFeat getPresenceFeat() {
        return presenceFeat;
    }

    /**
     * Sets the value of the presenceFeat property.
     * 
     * @param value
     *     allowed object is
     *     {@link PresenceFeat }
     *     
     */
    public void setPresenceFeat(PresenceFeat value) {
        this.presenceFeat = value;
    }

    /**
     * Gets the value of the imFeat property.
     * 
     * @return
     *     possible object is
     *     {@link IMFeat }
     *     
     */
    public IMFeat getIMFeat() {
        return imFeat;
    }

    /**
     * Sets the value of the imFeat property.
     * 
     * @param value
     *     allowed object is
     *     {@link IMFeat }
     *     
     */
    public void setIMFeat(IMFeat value) {
        this.imFeat = value;
    }

    /**
     * Gets the value of the groupFeat property.
     * 
     * @return
     *     possible object is
     *     {@link GroupFeat }
     *     
     */
    public GroupFeat getGroupFeat() {
        return groupFeat;
    }

    /**
     * Sets the value of the groupFeat property.
     * 
     * @param value
     *     allowed object is
     *     {@link GroupFeat }
     *     
     */
    public void setGroupFeat(GroupFeat value) {
        this.groupFeat = value;
    }

}
