//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.29 at 02:56:01 PM CEST 
//


package es.rickyepoderi.wbxml.bind.drmrel;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the es.rickyepoderi.wbxml.drmrel package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: es.rickyepoderi.wbxml.drmrel
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ODdPlay }
     * 
     */
    public ODdPlay createODdPlay() {
        return new ODdPlay();
    }

    /**
     * Create an instance of {@link OExConstraint }
     * 
     */
    public OExConstraint createOExConstraint() {
        return new OExConstraint();
    }

    /**
     * Create an instance of {@link ODdDisplay }
     * 
     */
    public ODdDisplay createODdDisplay() {
        return new ODdDisplay();
    }

    /**
     * Create an instance of {@link OExAsset }
     * 
     */
    public OExAsset createOExAsset() {
        return new OExAsset();
    }

    /**
     * Create an instance of {@link ODdDatetime }
     * 
     */
    public ODdDatetime createODdDatetime() {
        return new ODdDatetime();
    }

    /**
     * Create an instance of {@link ODdExecute }
     * 
     */
    public ODdExecute createODdExecute() {
        return new ODdExecute();
    }

    /**
     * Create an instance of {@link OExPermission }
     * 
     */
    public OExPermission createOExPermission() {
        return new OExPermission();
    }

    /**
     * Create an instance of {@link OExContext }
     * 
     */
    public OExContext createOExContext() {
        return new OExContext();
    }

    /**
     * Create an instance of {@link OExRights }
     * 
     */
    public OExRights createOExRights() {
        return new OExRights();
    }

    /**
     * Create an instance of {@link ODdPrint }
     * 
     */
    public ODdPrint createODdPrint() {
        return new ODdPrint();
    }

    /**
     * Create an instance of {@link OExAgreement }
     * 
     */
    public OExAgreement createOExAgreement() {
        return new OExAgreement();
    }

    /**
     * Create an instance of {@link DsKeyInfo }
     * 
     */
    public DsKeyInfo createDsKeyInfo() {
        return new DsKeyInfo();
    }

}
