//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.29 at 02:56:01 PM CEST 
//


package es.rickyepoderi.wbxml.bind.drmrel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "oDdStart",
    "oDdEnd"
})
@XmlRootElement(name = "datetime", namespace="http://odrl.net/1.1/ODRL-DD")
public class ODdDatetime {

    @XmlElement(name = "start", namespace="http://odrl.net/1.1/ODRL-DD")
    protected String oDdStart;
    @XmlElement(name = "end", namespace="http://odrl.net/1.1/ODRL-DD")
    protected String oDdEnd;

    /**
     * Gets the value of the oDdStart property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getODdStart() {
        return oDdStart;
    }

    /**
     * Sets the value of the oDdStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setODdStart(String value) {
        this.oDdStart = value;
    }

    /**
     * Gets the value of the oDdEnd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getODdEnd() {
        return oDdEnd;
    }

    /**
     * Sets the value of the oDdEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setODdEnd(String value) {
        this.oDdEnd = value;
    }

}
