//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.29 at 02:56:01 PM CEST 
//


package es.rickyepoderi.wbxml.bind.drmrel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "oExConstraint"
})
@XmlRootElement(name = "play", namespace="http://odrl.net/1.1/ODRL-DD")
public class ODdPlay {

    @XmlElement(name = "constraint", namespace="http://odrl.net/1.1/ODRL-EX")
    protected OExConstraint oExConstraint;

    /**
     * Gets the value of the oExConstraint property.
     * 
     * @return
     *     possible object is
     *     {@link OExConstraint }
     *     
     */
    public OExConstraint getOExConstraint() {
        return oExConstraint;
    }

    /**
     * Sets the value of the oExConstraint property.
     * 
     * @param value
     *     allowed object is
     *     {@link OExConstraint }
     *     
     */
    public void setOExConstraint(OExConstraint value) {
        this.oExConstraint = value;
    }

}
