//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.29 at 02:56:01 PM CEST 
//


package es.rickyepoderi.wbxml.bind.drmrel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "oExAsset",
    "oExPermission"
})
@XmlRootElement(name = "agreement", namespace="http://odrl.net/1.1/ODRL-EX")
public class OExAgreement {

    @XmlElement(name = "asset", namespace="http://odrl.net/1.1/ODRL-EX", required = true)
    protected OExAsset oExAsset;
    @XmlElement(name = "permission", namespace="http://odrl.net/1.1/ODRL-EX", required = true)
    protected OExPermission oExPermission;

    /**
     * Gets the value of the oExAsset property.
     * 
     * @return
     *     possible object is
     *     {@link OExAsset }
     *     
     */
    public OExAsset getOExAsset() {
        return oExAsset;
    }

    /**
     * Sets the value of the oExAsset property.
     * 
     * @param value
     *     allowed object is
     *     {@link OExAsset }
     *     
     */
    public void setOExAsset(OExAsset value) {
        this.oExAsset = value;
    }

    /**
     * Gets the value of the oExPermission property.
     * 
     * @return
     *     possible object is
     *     {@link OExPermission }
     *     
     */
    public OExPermission getOExPermission() {
        return oExPermission;
    }

    /**
     * Sets the value of the oExPermission property.
     * 
     * @param value
     *     allowed object is
     *     {@link OExPermission }
     *     
     */
    public void setOExPermission(OExPermission value) {
        this.oExPermission = value;
    }

}
