//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.29 at 02:56:01 PM CEST 
//


package es.rickyepoderi.wbxml.bind.drmrel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "oExContext",
    "dsKeyInfo"
})
@XmlRootElement(name = "asset", namespace="http://odrl.net/1.1/ODRL-EX")
public class OExAsset {

    @XmlElement(name = "context", namespace="http://odrl.net/1.1/ODRL-EX", required = true)
    protected OExContext oExContext;
    @XmlElement(name = "KeyInfo", namespace="http://www.w3.org/2000/09/xmldsig#/")
    protected DsKeyInfo dsKeyInfo;

    /**
     * Gets the value of the oExContext property.
     * 
     * @return
     *     possible object is
     *     {@link OExContext }
     *     
     */
    public OExContext getOExContext() {
        return oExContext;
    }

    /**
     * Sets the value of the oExContext property.
     * 
     * @param value
     *     allowed object is
     *     {@link OExContext }
     *     
     */
    public void setOExContext(OExContext value) {
        this.oExContext = value;
    }

    /**
     * Gets the value of the dsKeyInfo property.
     * 
     * @return
     *     possible object is
     *     {@link DsKeyInfo }
     *     
     */
    public DsKeyInfo getDsKeyInfo() {
        return dsKeyInfo;
    }

    /**
     * Sets the value of the dsKeyInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link DsKeyInfo }
     *     
     */
    public void setDsKeyInfo(DsKeyInfo value) {
        this.dsKeyInfo = value;
    }

}
