//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.29 at 02:56:01 PM CEST 
//


package es.rickyepoderi.wbxml.bind.drmrel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "oExContext",
    "oExAgreement"
})
@XmlRootElement(name = "rights", namespace="http://odrl.net/1.1/ODRL-EX")
public class OExRights {

    //@XmlAttribute(name = "xmlns:o-ex")
    //@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    //protected String xmlnsOEx;
    //@XmlAttribute(name = "xmlns:o-dd")
    //@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    //protected String xmlnsODd;
    //@XmlAttribute(name = "xmlns:ds")
    //@XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    //protected String xmlnsDs;
    @XmlElement(name = "context", namespace="http://odrl.net/1.1/ODRL-EX", required = true)
    protected OExContext oExContext;
    @XmlElement(name = "agreement", namespace="http://odrl.net/1.1/ODRL-EX", required = true)
    protected OExAgreement oExAgreement;

    /**
     * Gets the value of the xmlnsOEx property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
//    public String getXmlnsOEx() {
//        if (xmlnsOEx == null) {
//            return "http://odrl.net/1.1/ODRL-EX";
//        } else {
//            return xmlnsOEx;
//        }
//    }

    /**
     * Sets the value of the xmlnsOEx property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
//    public void setXmlnsOEx(String value) {
//        this.xmlnsOEx = value;
//    }

    /**
     * Gets the value of the xmlnsODd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
//    public String getXmlnsODd() {
//        if (xmlnsODd == null) {
//            return "http://odrl.net/1.1/ODRL-DD";
//        } else {
//            return xmlnsODd;
//        }
//    }

    /**
     * Sets the value of the xmlnsODd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
//    public void setXmlnsODd(String value) {
//        this.xmlnsODd = value;
//    }

    /**
     * Gets the value of the xmlnsDs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
//    public String getXmlnsDs() {
//        if (xmlnsDs == null) {
//            return "http://www.w3.org/2000/09/xmldsig#/";
//        } else {
//            return xmlnsDs;
//        }
//    }

    /**
     * Sets the value of the xmlnsDs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
//    public void setXmlnsDs(String value) {
//        this.xmlnsDs = value;
//    }

    /**
     * Gets the value of the oExContext property.
     * 
     * @return
     *     possible object is
     *     {@link OExContext }
     *     
     */
    public OExContext getOExContext() {
        return oExContext;
    }

    /**
     * Sets the value of the oExContext property.
     * 
     * @param value
     *     allowed object is
     *     {@link OExContext }
     *     
     */
    public void setOExContext(OExContext value) {
        this.oExContext = value;
    }

    /**
     * Gets the value of the oExAgreement property.
     * 
     * @return
     *     possible object is
     *     {@link OExAgreement }
     *     
     */
    public OExAgreement getOExAgreement() {
        return oExAgreement;
    }

    /**
     * Sets the value of the oExAgreement property.
     * 
     * @param value
     *     allowed object is
     *     {@link OExAgreement }
     *     
     */
    public void setOExAgreement(OExAgreement value) {
        this.oExAgreement = value;
    }

}
